categories_data = [
    {
        "id": 1,
        "name": "Freelancing",
        "description": "Offer your skills and services to clients worldwide",
        "count": 15,
        "totalOpportunities": "5M+ jobs",
        "color": "from-emerald-50 to-teal-50",
        "borderColor": "border-emerald-200",
        "textColor": "text-emerald-700"
    },
    {
        "id": 2,
        "name": "Surveys & Research",
        "description": "Share your opinions and get paid for your time",
        "count": 30,
        "totalOpportunities": "100K+ surveys",
        "color": "from-blue-50 to-cyan-50",
        "borderColor": "border-blue-200",
        "textColor": "text-blue-700"
    },
    {
        "id": 3,
        "name": "Digital Creators/Innovators",
        "description": "Create videos, blogs, and content for income",
        "count": 25,
        "totalOpportunities": "Unlimited opportunities",
        "color": "from-orange-50 to-amber-50",
        "borderColor": "border-orange-200",
        "textColor": "text-orange-700"
    },
    {
        "id": 4,
        "name": "Trading & Investing",
        "description": "Grow your wealth through stocks, crypto, and forex",
        "count": 15,
        "totalOpportunities": "1000+ assets",
        "color": "from-indigo-50 to-violet-50",
        "borderColor": "border-indigo-200",
        "textColor": "text-indigo-700"
    },
    {
        "id": 5,
        "name": "E-commerce",
        "description": "Sell products online through various platforms",
        "count": 20,
        "totalOpportunities": "500M+ customers",
        "color": "from-rose-50 to-pink-50",
        "borderColor": "border-rose-200",
        "textColor": "text-rose-700"
    },
    {
        "id": 6,
        "name": "Teaching & Tutoring",
        "description": "Share your knowledge and teach students online",
        "count": 15,
        "totalOpportunities": "50K+ courses",
        "color": "from-green-50 to-lime-50",
        "borderColor": "border-green-200",
        "textColor": "text-green-700"
    },
    {
        "id": 7,
        "name": "Remote Jobs",
        "description": "Find full-time or part-time remote employment",
        "count": 20,
        "totalOpportunities": "3M+ jobs",
        "color": "from-slate-50 to-gray-50",
        "borderColor": "border-slate-200",
        "textColor": "text-slate-700"
    },
    {
        "id": 8,
        "name": "Gig Economy",
        "description": "Complete short tasks and micro-jobs for quick cash",
        "count": 25,
        "totalOpportunities": "200K+ tasks",
        "color": "from-yellow-50 to-amber-50",
        "borderColor": "border-yellow-200",
        "textColor": "text-yellow-700"
    }
]

platforms_data = [
    # ==================== FREELANCING (15 platforms) ====================
    {
        "id": 1,
        "name": "Upwork",
        "category": "Freelancing",
        "description": "World's largest freelancing platform connecting businesses with independent professionals across all industries",
        "earningsPotential": "$1,000 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Bank Transfer", "Payoneer"],
        "featured": True,
        "link": "https://upwork.com"
    },
    {
        "id": 2,
        "name": "Fiverr",
        "category": "Freelancing",
        "description": "Marketplace for creative and digital services starting at $5, perfect for building a client base",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Bank Transfer", "Fiverr Revenue Card"],
        "featured": True,
        "link": "https://fiverr.com"
    },
    {
        "id": 3,
        "name": "Toptal",
        "category": "Freelancing",
        "description": "Elite freelance platform for top 3% of developers, designers, and finance experts. Premium rates.",
        "earningsPotential": "$5,000 - $15,000+/month",
        "difficulty": "Hard",
        "rating": 4.7,
        "minPayout": "$100",
        "paymentMethods": ["Bank Transfer", "Payoneer"],
        "featured": True,
        "link": "https://toptal.com"
    },
    {
        "id": 4,
        "name": "Freelancer.com",
        "category": "Freelancing",
        "description": "Global crowdsourcing marketplace with millions of projects across all skill levels",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$30",
        "paymentMethods": ["PayPal", "Bank Transfer", "Skrill"],
        "featured": False,
        "link": "https://freelancer.com"
    },
    {
        "id": 5,
        "name": "PeoplePerHour",
        "category": "Freelancing",
        "description": "UK-based platform popular with US clients for web development, design, and marketing projects",
        "earningsPotential": "$500 - $4,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://peopleperhour.com"
    },
    {
        "id": 6,
        "name": "Guru",
        "category": "Freelancing",
        "description": "Professional freelancing platform with lower fees and built-in collaboration tools",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer", "Check"],
        "featured": False,
        "link": "https://guru.com"
    },
    {
        "id": 7,
        "name": "Contra",
        "category": "Freelancing",
        "description": "Zero-commission freelance platform for tech professionals with AI portfolio features",
        "earningsPotential": "$1,000 - $8,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Crypto"],
        "featured": True,
        "link": "https://contra.com"
    },
    {
        "id": 8,
        "name": "99designs",
        "category": "Freelancing",
        "description": "Design-focused platform for logos, websites, and branding projects via contests or direct hire",
        "earningsPotential": "$500 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Payoneer"],
        "featured": False,
        "link": "https://99designs.com"
    },
    {
        "id": 9,
        "name": "Contently",
        "category": "Freelancing",
        "description": "Premium content marketing platform connecting writers with major brands like Coca-Cola and IBM",
        "earningsPotential": "$2,000 - $10,000+/month",
        "difficulty": "Hard",
        "rating": 4.5,
        "minPayout": "$100",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://contently.com"
    },
    {
        "id": 10,
        "name": "Dribbble",
        "category": "Freelancing",
        "description": "Design community and job board for graphic designers, illustrators, and UI/UX professionals",
        "earningsPotential": "$1,000 - $6,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "Varies",
        "paymentMethods": ["Direct hire - negotiated"],
        "featured": False,
        "link": "https://dribbble.com"
    },
    {
        "id": 11,
        "name": "Behance",
        "category": "Freelancing",
        "description": "Adobe's creative portfolio platform with job opportunities from top companies worldwide",
        "earningsPotential": "$1,000 - $8,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "Varies",
        "paymentMethods": ["Direct hire - negotiated"],
        "featured": False,
        "link": "https://behance.net"
    },
    {
        "id": 12,
        "name": "SolidGigs",
        "category": "Freelancing",
        "description": "Curated freelance job listings delivered to your inbox - best gigs handpicked for you",
        "earningsPotential": "$1,000 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Varies",
        "paymentMethods": ["Direct hire - negotiated"],
        "featured": False,
        "link": "https://solidgigs.com"
    },
    {
        "id": 13,
        "name": "Twine",
        "category": "Freelancing",
        "description": "Creative freelance marketplace for video production, animation, and design professionals",
        "earningsPotential": "$500 - $4,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://twine.net"
    },
    {
        "id": 14,
        "name": "CloudPeeps",
        "category": "Freelancing",
        "description": "Marketing and content freelancers connecting with startups and growing businesses",
        "earningsPotential": "$1,000 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$100",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://cloudpeeps.com"
    },
    {
        "id": 15,
        "name": "Catalant",
        "category": "Freelancing",
        "description": "Enterprise consulting marketplace for business strategy and management consulting projects",
        "earningsPotential": "$5,000 - $20,000+/month",
        "difficulty": "Hard",
        "rating": 4.3,
        "minPayout": "$500",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://catalant.com"
    },
    
    # ==================== SURVEYS & RESEARCH (30 platforms) ====================
    {
        "id": 16,
        "name": "Swagbucks",
        "category": "Surveys & Research",
        "description": "Earn points for surveys, watching videos, shopping online, and playing games. Redeem for cash or gift cards.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$3",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": True,
        "link": "https://swagbucks.com"
    },
    {
        "id": 17,
        "name": "Survey Junkie",
        "category": "Surveys & Research",
        "description": "One of the highest-rated survey sites with fast payouts and consistent survey availability",
        "earningsPotential": "$40 - $150/month",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Bank Transfer", "Gift Cards"],
        "featured": True,
        "link": "https://surveyjunkie.com"
    },
    {
        "id": 18,
        "name": "Prolific",
        "category": "Surveys & Research",
        "description": "Academic research platform with the highest pay rates in the industry - $8+/hour minimum",
        "earningsPotential": "$100 - $400/month",
        "difficulty": "Easy",
        "rating": 4.8,
        "minPayout": "$5",
        "paymentMethods": ["PayPal"],
        "featured": True,
        "link": "https://prolific.co"
    },
    {
        "id": 19,
        "name": "InboxDollars",
        "category": "Surveys & Research",
        "description": "Paid over $80 million to members. Earn for surveys, emails, games, and shopping. $5 signup bonus.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$30",
        "paymentMethods": ["Check", "PayPal", "Gift Cards"],
        "featured": True,
        "link": "https://inboxdollars.com"
    },
    {
        "id": 20,
        "name": "MyPoints",
        "category": "Surveys & Research",
        "description": "Earn points for surveys, shopping, and watching videos. Part of the Swagbucks family.",
        "earningsPotential": "$30 - $150/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://mypoints.com"
    },
    {
        "id": 21,
        "name": "Branded Surveys",
        "category": "Surveys & Research",
        "description": "High-paying surveys with loyalty bonuses. 100-point signup bonus for new members.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Bank Transfer", "Gift Cards"],
        "featured": False,
        "link": "https://surveys.gobranded.com"
    },
    {
        "id": 22,
        "name": "Pinecone Research",
        "category": "Surveys & Research",
        "description": "Invite-only panel paying $3-5 per survey. Test products and influence future products.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.5,
        "minPayout": "$3",
        "paymentMethods": ["PayPal", "Check", "Gift Cards"],
        "featured": False,
        "link": "https://pineconeresearch.com"
    },
    {
        "id": 23,
        "name": "Opinion Outpost",
        "category": "Surveys & Research",
        "description": "Quick surveys with instant rewards. Chance to win $10,000 quarterly prize.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Amazon Gift Cards"],
        "featured": False,
        "link": "https://opinionoutpost.com"
    },
    {
        "id": 24,
        "name": "Toluna",
        "category": "Surveys & Research",
        "description": "Global survey community with product testing opportunities and community features",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://toluna.com"
    },
    {
        "id": 25,
        "name": "LifePoints",
        "category": "Surveys & Research",
        "description": "Earn points for surveys on consumer products. Trusted panel with 5 million+ members.",
        "earningsPotential": "$25 - $80/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://lifepoints.com"
    },
    {
        "id": 26,
        "name": "PrizeRebel",
        "category": "Surveys & Research",
        "description": "GPT site with surveys, offers, and tasks. Level system unlocks better rewards.",
        "earningsPotential": "$30 - $150/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$2",
        "paymentMethods": ["PayPal", "Bitcoin", "Gift Cards"],
        "featured": False,
        "link": "https://prizerebel.com"
    },
    {
        "id": 27,
        "name": "Google Opinion Rewards",
        "category": "Surveys & Research",
        "description": "Quick surveys from Google paying in Play Store credits or PayPal (iOS)",
        "earningsPotential": "$10 - $40/month",
        "difficulty": "Easy",
        "rating": 4.5,
        "minPayout": "$2",
        "paymentMethods": ["Google Play Credit", "PayPal (iOS)"],
        "featured": False,
        "link": "https://surveys.google.com/google-opinion-rewards"
    },
    {
        "id": 28,
        "name": "Qmee",
        "category": "Surveys & Research",
        "description": "Instant PayPal cashouts with no minimum. Earn for surveys and web searches.",
        "earningsPotential": "$20 - $80/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$0.01",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://qmee.com"
    },
    {
        "id": 29,
        "name": "Forthright",
        "category": "Surveys & Research",
        "description": "Transparent surveys that show pay upfront. Direct PayPal payments.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$1",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://forthright.com"
    },
    {
        "id": 30,
        "name": "Attapoll",
        "category": "Surveys & Research",
        "description": "Mobile survey app with instant PayPal payments and good survey matching",
        "earningsPotential": "$20 - $80/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$3",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://attapoll.com"
    },
    {
        "id": 31,
        "name": "YouGov",
        "category": "Surveys & Research",
        "description": "Political and opinion polling with consistent survey availability",
        "earningsPotential": "$20 - $60/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$15",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://yougov.com"
    },
    {
        "id": 32,
        "name": "Ipsos iSay",
        "category": "Surveys & Research",
        "description": "Major market research company with loyalty rewards and prize draws",
        "earningsPotential": "$20 - $70/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Gift Cards", "Virtual Visa"],
        "featured": False,
        "link": "https://social.i-say.com"
    },
    {
        "id": 33,
        "name": "Five Surveys",
        "category": "Surveys & Research",
        "description": "Guaranteed $1 per survey with $5 minimum cashout. Simple and reliable.",
        "earningsPotential": "$25 - $100/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Amazon Gift Cards"],
        "featured": False,
        "link": "https://fivesurveys.com"
    },
    {
        "id": 34,
        "name": "Prime Opinion",
        "category": "Surveys & Research",
        "description": "New survey site with signup bonus and mobile app for on-the-go earning",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://primeopinion.com"
    },
    {
        "id": 35,
        "name": "PaidViewpoint",
        "category": "Surveys & Research",
        "description": "High-rated for reliability. Trait Score system unlocks higher-paying surveys.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$15",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://paidviewpoint.com"
    },
    {
        "id": 36,
        "name": "UserTesting",
        "category": "Surveys & Research",
        "description": "Test websites and apps while sharing your thoughts. $10 per 20-minute test.",
        "earningsPotential": "$100 - $400/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["PayPal"],
        "featured": True,
        "link": "https://usertesting.com"
    },
    {
        "id": 37,
        "name": "Userlytics",
        "category": "Surveys & Research",
        "description": "UX testing platform paying for website and app feedback. Video recording required.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$10",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://userlytics.com"
    },
    {
        "id": 38,
        "name": "TryMyUI",
        "category": "Surveys & Research",
        "description": "Usability testing paying $10 per test. Record your screen while testing websites.",
        "earningsPotential": "$50 - $150/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$10",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://trymyui.com"
    },
    {
        "id": 39,
        "name": "uTest",
        "category": "Surveys & Research",
        "description": "Software testing community with bug bounties and exploratory testing projects",
        "earningsPotential": "$100 - $500/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Payoneer"],
        "featured": False,
        "link": "https://utest.com"
    },
    {
        "id": 40,
        "name": "Testbirds",
        "category": "Surveys & Research",
        "description": "Crowdsourced testing platform for apps, websites, and IoT devices",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://testbirds.com"
    },
    {
        "id": 41,
        "name": "Crowdtap",
        "category": "Surveys & Research",
        "description": "Earn gift cards for short surveys and product sampling missions",
        "earningsPotential": "$20 - $80/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["Gift Cards"],
        "featured": False,
        "link": "https://crowdtap.com"
    },
    {
        "id": 42,
        "name": "Panel Station",
        "category": "Surveys & Research",
        "description": "International survey panel with good availability for US residents",
        "earningsPotential": "$20 - $60/month",
        "difficulty": "Easy",
        "rating": 3.8,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://thepanelstation.com"
    },
    {
        "id": 43,
        "name": "Valued Opinions",
        "category": "Surveys & Research",
        "description": "Earn up to $5 per survey with gift card rewards from major retailers",
        "earningsPotential": "$20 - $80/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$10",
        "paymentMethods": ["Gift Cards"],
        "featured": False,
        "link": "https://valuedopinions.com"
    },
    {
        "id": 44,
        "name": "Rakuten Insights",
        "category": "Surveys & Research",
        "description": "Earn points for market research surveys redeemable for cash or gift cards",
        "earningsPotential": "$15 - $50/month",
        "difficulty": "Easy",
        "rating": 3.8,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Amazon Gift Cards"],
        "featured": False,
        "link": "https://insight.rakuten.com"
    },
    {
        "id": 45,
        "name": "Clickworker",
        "category": "Surveys & Research",
        "description": "Microtasks including surveys, data entry, AI training, and content creation",
        "earningsPotential": "$50 - $300/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "SEPA"],
        "featured": False,
        "link": "https://clickworker.com"
    },
    
    # ==================== DIGITAL CREATORS (25 platforms) ====================
    {
        "id": 46,
        "name": "YouTube",
        "category": "Digital Creators/Innovators",
        "description": "World's largest video platform. Earn from ads, memberships, Super Chat, and sponsorships.",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.7,
        "minPayout": "$100",
        "paymentMethods": ["Bank Transfer", "Check"],
        "featured": True,
        "link": "https://youtube.com/creators"
    },
    {
        "id": 47,
        "name": "TikTok Creator Fund",
        "category": "Digital Creators/Innovators",
        "description": "Earn from short-form video views, LIVE gifts, and brand partnerships",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Zelle"],
        "featured": True,
        "link": "https://tiktok.com/creators"
    },
    {
        "id": 48,
        "name": "Twitch",
        "category": "Digital Creators/Innovators",
        "description": "Live streaming platform for gaming, music, and creative content. Earn from subs and bits.",
        "earningsPotential": "$100 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Bank Transfer", "Check"],
        "featured": True,
        "link": "https://twitch.tv"
    },
    {
        "id": 49,
        "name": "Patreon",
        "category": "Digital Creators/Innovators",
        "description": "Membership platform for creators to earn recurring income from fans and supporters",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer", "Payoneer"],
        "featured": True,
        "link": "https://patreon.com"
    },
    {
        "id": 50,
        "name": "Substack",
        "category": "Digital Creators/Innovators",
        "description": "Newsletter platform for writers to build paid subscriber bases. Keep 90% of revenue.",
        "earningsPotential": "$100 - $100,000+/month",
        "difficulty": "Medium",
        "rating": 4.6,
        "minPayout": "$10",
        "paymentMethods": ["Bank Transfer", "Stripe"],
        "featured": True,
        "link": "https://substack.com"
    },
    {
        "id": 51,
        "name": "Medium Partner Program",
        "category": "Digital Creators/Innovators",
        "description": "Earn based on member reading time. Write about any topic for a built-in audience.",
        "earningsPotential": "$50 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$10",
        "paymentMethods": ["Bank Transfer", "PayPal", "Stripe"],
        "featured": False,
        "link": "https://medium.com/creators"
    },
    {
        "id": 52,
        "name": "Spotify for Podcasters",
        "category": "Digital Creators/Innovators",
        "description": "Distribute your podcast everywhere and monetize with ads and subscriptions",
        "earningsPotential": "$50 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["Bank Transfer", "PayPal"],
        "featured": False,
        "link": "https://podcasters.spotify.com"
    },
    {
        "id": 53,
        "name": "Shutterstock Contributor",
        "category": "Digital Creators/Innovators",
        "description": "Sell photos, videos, and music. Earn royalties up to 40% per download.",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$35",
        "paymentMethods": ["PayPal", "Payoneer", "Skrill"],
        "featured": False,
        "link": "https://submit.shutterstock.com"
    },
    {
        "id": 54,
        "name": "Adobe Stock Contributor",
        "category": "Digital Creators/Innovators",
        "description": "Sell photos, vectors, and videos to millions of Adobe Creative Cloud users",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Skrill"],
        "featured": False,
        "link": "https://stock.adobe.com/contributor"
    },
    {
        "id": 55,
        "name": "Getty Images",
        "category": "Digital Creators/Innovators",
        "description": "Premium stock photography platform for professional photographers",
        "earningsPotential": "$200 - $10,000+/month",
        "difficulty": "Hard",
        "rating": 4.3,
        "minPayout": "$100",
        "paymentMethods": ["Bank Transfer", "PayPal"],
        "featured": False,
        "link": "https://gettyimages.com/workwithus"
    },
    {
        "id": 56,
        "name": "Alamy",
        "category": "Digital Creators/Innovators",
        "description": "Stock photo site offering up to 50% commission - one of the highest in the industry",
        "earningsPotential": "$100 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Skrill", "Bank Transfer"],
        "featured": False,
        "link": "https://alamy.com"
    },
    {
        "id": 57,
        "name": "Ko-fi",
        "category": "Digital Creators/Innovators",
        "description": "Accept one-time donations and memberships. 0% platform fee on donations.",
        "earningsPotential": "$50 - $5,000+/month",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Stripe"],
        "featured": False,
        "link": "https://ko-fi.com"
    },
    {
        "id": 58,
        "name": "Gumroad",
        "category": "Digital Creators/Innovators",
        "description": "Sell digital products, courses, and memberships directly to your audience",
        "earningsPotential": "$100 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://gumroad.com"
    },
    {
        "id": 59,
        "name": "Redbubble",
        "category": "Digital Creators/Innovators",
        "description": "Upload designs and sell on 70+ products. Print-on-demand with no inventory needed.",
        "earningsPotential": "$50 - $3,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://redbubble.com"
    },
    {
        "id": 60,
        "name": "Envato Elements Contributor",
        "category": "Digital Creators/Innovators",
        "description": "Sell templates, graphics, and digital assets to creative professionals worldwide",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Skrill", "Bank Transfer"],
        "featured": False,
        "link": "https://envato.com"
    },
    {
        "id": 61,
        "name": "Mighty Networks",
        "category": "Digital Creators/Innovators",
        "description": "Build your own community and membership site. Average membership: $48/month",
        "earningsPotential": "$200 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "Varies",
        "paymentMethods": ["Stripe"],
        "featured": False,
        "link": "https://mightynetworks.com"
    },
    {
        "id": 62,
        "name": "Teachable",
        "category": "Digital Creators/Innovators",
        "description": "Create and sell online courses with your own branded school",
        "earningsPotential": "$100 - $100,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://teachable.com"
    },
    {
        "id": 63,
        "name": "Thinkific",
        "category": "Digital Creators/Innovators",
        "description": "Course creation platform with no transaction fees on paid plans",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$50",
        "paymentMethods": ["Stripe", "PayPal"],
        "featured": False,
        "link": "https://thinkific.com"
    },
    {
        "id": 64,
        "name": "Podia",
        "category": "Digital Creators/Innovators",
        "description": "All-in-one platform for courses, downloads, and community with email marketing built-in",
        "earningsPotential": "$100 - $30,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$50",
        "paymentMethods": ["Stripe", "PayPal"],
        "featured": False,
        "link": "https://podia.com"
    },
    {
        "id": 65,
        "name": "Instagram Creator",
        "category": "Digital Creators/Innovators",
        "description": "Monetize through brand deals, subscriptions, badges, and affiliate marketing",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$25",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://business.instagram.com/creators"
    },
    {
        "id": 66,
        "name": "Pinterest Creator",
        "category": "Digital Creators/Innovators",
        "description": "Earn from Idea Pins and brand partnerships. Great for lifestyle and DIY content.",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$25",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://business.pinterest.com/creators"
    },
    {
        "id": 67,
        "name": "Snapchat Spotlight",
        "category": "Digital Creators/Innovators",
        "description": "Earn from viral short-form videos. Over $1 million paid daily to creators.",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$100",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://creators.snap.com"
    },
    {
        "id": 68,
        "name": "LinkedIn Creator",
        "category": "Digital Creators/Innovators",
        "description": "Build thought leadership and attract consulting clients or job offers",
        "earningsPotential": "$100 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Varies",
        "paymentMethods": ["Direct hire - negotiated"],
        "featured": False,
        "link": "https://linkedin.com/creators"
    },
    {
        "id": 69,
        "name": "Twitter/X Subscriptions",
        "category": "Digital Creators/Innovators",
        "description": "Offer premium content to subscribers and earn from ad revenue sharing",
        "earningsPotential": "$50 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 3.8,
        "minPayout": "$50",
        "paymentMethods": ["Bank Transfer", "Stripe"],
        "featured": False,
        "link": "https://x.com"
    },
    {
        "id": 70,
        "name": "Collabstr",
        "category": "Digital Creators/Innovators",
        "description": "Connect with brands for paid collaborations across fashion, beauty, and lifestyle",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Varies",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://collabstr.com"
    },
    
    # ==================== TRADING & INVESTING (15 platforms) ====================
    {
        "id": 71,
        "name": "Robinhood",
        "category": "Trading & Investing",
        "description": "Commission-free trading for stocks, ETFs, options, and crypto. Popular with beginners.",
        "earningsPotential": "Varies with investment",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": True,
        "link": "https://robinhood.com"
    },
    {
        "id": 72,
        "name": "Coinbase",
        "category": "Trading & Investing",
        "description": "Leading cryptocurrency exchange in the US. Earn rewards through staking and learning.",
        "earningsPotential": "Varies with investment",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "PayPal", "Crypto"],
        "featured": True,
        "link": "https://coinbase.com"
    },
    {
        "id": 73,
        "name": "Acorns",
        "category": "Trading & Investing",
        "description": "Micro-investing app that rounds up purchases and invests the change automatically",
        "earningsPotential": "Varies with investment",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": True,
        "link": "https://acorns.com"
    },
    {
        "id": 74,
        "name": "Fundrise",
        "category": "Trading & Investing",
        "description": "Real estate crowdfunding with potential 7-23% returns. Start with just $10.",
        "earningsPotential": "$100 - $5,000+/year",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://fundrise.com"
    },
    {
        "id": 75,
        "name": "M1 Finance",
        "category": "Trading & Investing",
        "description": "Free automated investing with customizable portfolios. Great for dividend investing.",
        "earningsPotential": "Varies with investment",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://m1finance.com"
    },
    {
        "id": 76,
        "name": "Webull",
        "category": "Trading & Investing",
        "description": "Commission-free trading with advanced charts and extended hours trading",
        "earningsPotential": "Varies with investment",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://webull.com"
    },
    {
        "id": 77,
        "name": "Public",
        "category": "Trading & Investing",
        "description": "Social investing platform for stocks and crypto with community features",
        "earningsPotential": "Varies with investment",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://public.com"
    },
    {
        "id": 78,
        "name": "Stash",
        "category": "Trading & Investing",
        "description": "Beginner-friendly investing app with fractional shares and banking features",
        "earningsPotential": "Varies with investment",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://stash.com"
    },
    {
        "id": 79,
        "name": "Groundfloor",
        "category": "Trading & Investing",
        "description": "Real estate debt investing with 6-14% potential returns. Start with $10.",
        "earningsPotential": "$100 - $3,000+/year",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$10",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://groundfloor.com"
    },
    {
        "id": 80,
        "name": "Betterment",
        "category": "Trading & Investing",
        "description": "Robo-advisor with automated portfolio management and tax-loss harvesting",
        "earningsPotential": "Varies with investment",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://betterment.com"
    },
    {
        "id": 81,
        "name": "Wealthfront",
        "category": "Trading & Investing",
        "description": "Automated investing with tax optimization. Free financial planning tools.",
        "earningsPotential": "Varies with investment",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://wealthfront.com"
    },
    {
        "id": 82,
        "name": "SoFi Invest",
        "category": "Trading & Investing",
        "description": "Commission-free trading with banking, loans, and crypto all in one app",
        "earningsPotential": "Varies with investment",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://sofi.com/invest"
    },
    {
        "id": 83,
        "name": "Kraken",
        "category": "Trading & Investing",
        "description": "Advanced crypto exchange with staking rewards and margin trading",
        "earningsPotential": "Varies with investment",
        "difficulty": "Hard",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Crypto"],
        "featured": False,
        "link": "https://kraken.com"
    },
    {
        "id": 84,
        "name": "Gemini",
        "category": "Trading & Investing",
        "description": "Regulated crypto exchange with earn program for passive income on holdings",
        "earningsPotential": "Varies with investment",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Crypto"],
        "featured": False,
        "link": "https://gemini.com"
    },
    {
        "id": 85,
        "name": "Yieldstreet",
        "category": "Trading & Investing",
        "description": "Alternative investments in art, real estate, and private credit",
        "earningsPotential": "$500 - $10,000+/year",
        "difficulty": "Hard",
        "rating": 4.0,
        "minPayout": "$500",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://yieldstreet.com"
    },
    
    # ==================== E-COMMERCE (20 platforms) ====================
    {
        "id": 86,
        "name": "Amazon FBA",
        "category": "E-commerce",
        "description": "Sell products on Amazon with fulfillment handled by Amazon. Access to Prime customers.",
        "earningsPotential": "$500 - $100,000+/month",
        "difficulty": "Hard",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": True,
        "link": "https://sell.amazon.com"
    },
    {
        "id": 87,
        "name": "Etsy",
        "category": "E-commerce",
        "description": "Marketplace for handmade, vintage, and unique items. 90+ million active buyers.",
        "earningsPotential": "$100 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": True,
        "link": "https://etsy.com"
    },
    {
        "id": 88,
        "name": "eBay",
        "category": "E-commerce",
        "description": "Sell new or used items through auctions or fixed-price listings to global buyers",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": True,
        "link": "https://ebay.com"
    },
    {
        "id": 89,
        "name": "Shopify",
        "category": "E-commerce",
        "description": "Build your own online store with dropshipping or your own products",
        "earningsPotential": "$100 - $500,000+/month",
        "difficulty": "Medium",
        "rating": 4.6,
        "minPayout": "$0",
        "paymentMethods": ["Shopify Payments", "PayPal"],
        "featured": True,
        "link": "https://shopify.com"
    },
    {
        "id": 90,
        "name": "Poshmark",
        "category": "E-commerce",
        "description": "Social marketplace for fashion. Sell clothes, shoes, and accessories from your closet.",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$20",
        "paymentMethods": ["Bank Transfer", "Check"],
        "featured": False,
        "link": "https://poshmark.com"
    },
    {
        "id": 91,
        "name": "Mercari",
        "category": "E-commerce",
        "description": "Easy-to-use selling app for anything from clothes to electronics",
        "earningsPotential": "$50 - $5,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$10",
        "paymentMethods": ["Bank Transfer", "Instant Pay"],
        "featured": False,
        "link": "https://mercari.com"
    },
    {
        "id": 92,
        "name": "Facebook Marketplace",
        "category": "E-commerce",
        "description": "Sell locally or ship nationwide to Facebook's massive user base",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Cash", "PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://facebook.com/marketplace"
    },
    {
        "id": 93,
        "name": "Depop",
        "category": "E-commerce",
        "description": "Gen-Z focused fashion marketplace for vintage, streetwear, and unique styles",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://depop.com"
    },
    {
        "id": 94,
        "name": "ThredUp",
        "category": "E-commerce",
        "description": "Send in clothes to sell - they handle photos, listings, and shipping",
        "earningsPotential": "$50 - $500/month",
        "difficulty": "Easy",
        "rating": 3.8,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Prepaid Card"],
        "featured": False,
        "link": "https://thredup.com"
    },
    {
        "id": 95,
        "name": "Walmart Marketplace",
        "category": "E-commerce",
        "description": "Sell on Walmart.com alongside major brands. Growing alternative to Amazon.",
        "earningsPotential": "$500 - $50,000+/month",
        "difficulty": "Hard",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://marketplace.walmart.com"
    },
    {
        "id": 96,
        "name": "Amazon Merch on Demand",
        "category": "E-commerce",
        "description": "Design t-shirts and Amazon handles printing, shipping, and customer service",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://merch.amazon.com"
    },
    {
        "id": 97,
        "name": "Printful",
        "category": "E-commerce",
        "description": "Print-on-demand for apparel and products. Integrates with your online store.",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://printful.com"
    },
    {
        "id": 98,
        "name": "Teespring/Spring",
        "category": "E-commerce",
        "description": "Create and sell custom merchandise without upfront costs",
        "earningsPotential": "$50 - $5,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Payoneer"],
        "featured": False,
        "link": "https://spri.ng"
    },
    {
        "id": 99,
        "name": "Bonanza",
        "category": "E-commerce",
        "description": "Alternative marketplace with lower fees than eBay and Amazon",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://bonanza.com"
    },
    {
        "id": 100,
        "name": "Reverb",
        "category": "E-commerce",
        "description": "Marketplace for new and used musical instruments and gear",
        "earningsPotential": "$100 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://reverb.com"
    },
    {
        "id": 101,
        "name": "StockX",
        "category": "E-commerce",
        "description": "Resell sneakers, streetwear, and collectibles with authentication guarantee",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://stockx.com"
    },
    {
        "id": 102,
        "name": "GOAT",
        "category": "E-commerce",
        "description": "Sneaker marketplace with authentication for buying and selling kicks",
        "earningsPotential": "$100 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://goat.com"
    },
    {
        "id": 103,
        "name": "Whatnot",
        "category": "E-commerce",
        "description": "Live shopping platform for collectibles, cards, and vintage items",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://whatnot.com"
    },
    {
        "id": 104,
        "name": "Decluttr",
        "category": "E-commerce",
        "description": "Sell tech, DVDs, and games instantly with upfront pricing - no listing needed",
        "earningsPotential": "$50 - $500/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Bank Transfer", "Check"],
        "featured": False,
        "link": "https://decluttr.com"
    },
    {
        "id": 105,
        "name": "Ruby Lane",
        "category": "E-commerce",
        "description": "Upscale marketplace for antiques, vintage items, and collectibles",
        "earningsPotential": "$200 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Check"],
        "featured": False,
        "link": "https://rubylane.com"
    },
    
    # ==================== TEACHING & TUTORING (15 platforms) ====================
    {
        "id": 106,
        "name": "Udemy",
        "category": "Teaching & Tutoring",
        "description": "Create and sell courses to millions of students. You keep 37-97% of revenue.",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Payoneer", "Bank Transfer"],
        "featured": True,
        "link": "https://udemy.com"
    },
    {
        "id": 107,
        "name": "Skillshare Teacher",
        "category": "Teaching & Tutoring",
        "description": "Earn royalties based on minutes watched. Great for creative and business topics.",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Stripe"],
        "featured": False,
        "link": "https://skillshare.com/teach"
    },
    {
        "id": 108,
        "name": "Wyzant",
        "category": "Teaching & Tutoring",
        "description": "Connect with students for 1-on-1 tutoring. Set your own rates, over 300 subjects.",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$25",
        "paymentMethods": ["Bank Transfer"],
        "featured": True,
        "link": "https://wyzant.com"
    },
    {
        "id": 109,
        "name": "Preply",
        "category": "Teaching & Tutoring",
        "description": "Teach languages and academic subjects to students worldwide via video",
        "earningsPotential": "$500 - $4,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Skrill", "Payoneer"],
        "featured": False,
        "link": "https://preply.com"
    },
    {
        "id": 110,
        "name": "Cambly",
        "category": "Teaching & Tutoring",
        "description": "Chat with English learners worldwide. $10.20/hour for conversations.",
        "earningsPotential": "$200 - $1,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$20",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://cambly.com"
    },
    {
        "id": 111,
        "name": "iTalki",
        "category": "Teaching & Tutoring",
        "description": "Teach your native language to students worldwide. Set your own schedule and rates.",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Skrill", "Bank Transfer"],
        "featured": False,
        "link": "https://italki.com"
    },
    {
        "id": 112,
        "name": "Tutor.com",
        "category": "Teaching & Tutoring",
        "description": "Work with K-12 and college students. Flexible scheduling, paid training provided.",
        "earningsPotential": "$500 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Varies",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://tutor.com"
    },
    {
        "id": 113,
        "name": "Chegg Tutors",
        "category": "Teaching & Tutoring",
        "description": "Tutor college students in over 100 subjects. $20+/hour for experienced tutors.",
        "earningsPotential": "$300 - $2,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://chegg.com/tutors"
    },
    {
        "id": 114,
        "name": "VIPKid",
        "category": "Teaching & Tutoring",
        "description": "Teach English to children in China. Flexible hours, $14-22/hour.",
        "earningsPotential": "$500 - $2,500+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$100",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://vipkid.com"
    },
    {
        "id": 115,
        "name": "Outschool",
        "category": "Teaching & Tutoring",
        "description": "Teach live online classes to K-12 students. Set your own curriculum and prices.",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://outschool.com"
    },
    {
        "id": 116,
        "name": "Varsity Tutors",
        "category": "Teaching & Tutoring",
        "description": "Premium tutoring platform connecting you with students nationwide",
        "earningsPotential": "$500 - $4,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Varies",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://varsitytutors.com"
    },
    {
        "id": 117,
        "name": "Course Hero",
        "category": "Teaching & Tutoring",
        "description": "Answer student questions and earn per response. Great for subject experts.",
        "earningsPotential": "$200 - $2,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$50",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://coursehero.com/tutors"
    },
    {
        "id": 118,
        "name": "Studypool",
        "category": "Teaching & Tutoring",
        "description": "Answer homework questions and provide tutoring. Set your own rates.",
        "earningsPotential": "$200 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 3.9,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://studypool.com"
    },
    {
        "id": 119,
        "name": "Lingoda",
        "category": "Teaching & Tutoring",
        "description": "Teach English, German, French, or Spanish in small group classes",
        "earningsPotential": "$500 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Varies",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://lingoda.com"
    },
    {
        "id": 120,
        "name": "TakeLessons",
        "category": "Teaching & Tutoring",
        "description": "Teach music, languages, or academic subjects. Set your own rates and schedule.",
        "earningsPotential": "$300 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://takelessons.com"
    },
    
    # ==================== REMOTE JOBS (20 platforms) ====================
    {
        "id": 121,
        "name": "FlexJobs",
        "category": "Remote Jobs",
        "description": "Hand-screened remote job listings. No scams, all legitimate opportunities.",
        "earningsPotential": "$2,000 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": True,
        "link": "https://flexjobs.com"
    },
    {
        "id": 122,
        "name": "We Work Remotely",
        "category": "Remote Jobs",
        "description": "Largest remote work community. Tech, marketing, and customer support jobs.",
        "earningsPotential": "$3,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": True,
        "link": "https://weworkremotely.com"
    },
    {
        "id": 123,
        "name": "Remote OK",
        "category": "Remote Jobs",
        "description": "Remote jobs in programming, marketing, and design from startups to Fortune 500",
        "earningsPotential": "$3,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://remoteok.com"
    },
    {
        "id": 124,
        "name": "Indeed Remote",
        "category": "Remote Jobs",
        "description": "Filter Indeed's massive job board for remote-only positions",
        "earningsPotential": "$2,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://indeed.com/q-remote-jobs"
    },
    {
        "id": 125,
        "name": "LinkedIn Jobs",
        "category": "Remote Jobs",
        "description": "Professional network with extensive remote job listings and easy apply",
        "earningsPotential": "$2,500 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": True,
        "link": "https://linkedin.com/jobs"
    },
    {
        "id": 126,
        "name": "AngelList",
        "category": "Remote Jobs",
        "description": "Startup jobs with equity opportunities. Many remote-first companies.",
        "earningsPotential": "$3,000 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://angel.co"
    },
    {
        "id": 127,
        "name": "Remotive",
        "category": "Remote Jobs",
        "description": "Curated remote jobs in tech, marketing, and HR. Newsletter with latest listings.",
        "earningsPotential": "$3,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://remotive.com"
    },
    {
        "id": 128,
        "name": "JustRemote",
        "category": "Remote Jobs",
        "description": "Remote jobs categorized by type with filters for experience level",
        "earningsPotential": "$2,500 - $12,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://justremote.co"
    },
    {
        "id": 129,
        "name": "Working Nomads",
        "category": "Remote Jobs",
        "description": "Daily remote job listings curated for digital nomads",
        "earningsPotential": "$2,500 - $12,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://workingnomads.co"
    },
    {
        "id": 130,
        "name": "Virtual Vocations",
        "category": "Remote Jobs",
        "description": "Hand-screened telecommute jobs with resume and cover letter help",
        "earningsPotential": "$2,000 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://virtualvocations.com"
    },
    {
        "id": 131,
        "name": "Remote.co",
        "category": "Remote Jobs",
        "description": "Remote jobs from top remote-friendly companies worldwide",
        "earningsPotential": "$2,500 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://remote.co"
    },
    {
        "id": 132,
        "name": "Glassdoor Remote",
        "category": "Remote Jobs",
        "description": "Remote jobs with salary info and company reviews from employees",
        "earningsPotential": "$2,500 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://glassdoor.com"
    },
    {
        "id": 133,
        "name": "Dice",
        "category": "Remote Jobs",
        "description": "Tech-focused job board with many remote software and IT positions",
        "earningsPotential": "$4,000 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://dice.com"
    },
    {
        "id": 134,
        "name": "Hired",
        "category": "Remote Jobs",
        "description": "Tech job marketplace where companies apply to you. Salary upfront.",
        "earningsPotential": "$5,000 - $25,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://hired.com"
    },
    {
        "id": 135,
        "name": "Turing",
        "category": "Remote Jobs",
        "description": "Remote developer jobs with US companies. Rigorous vetting for top talent.",
        "earningsPotential": "$5,000 - $20,000+/month",
        "difficulty": "Hard",
        "rating": 4.2,
        "minPayout": "Salary",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://turing.com"
    },
    {
        "id": 136,
        "name": "Arc",
        "category": "Remote Jobs",
        "description": "Remote developer jobs with salary transparency and skill matching",
        "earningsPotential": "$4,000 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Salary",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://arc.dev"
    },
    {
        "id": 137,
        "name": "Crossover",
        "category": "Remote Jobs",
        "description": "High-paying remote positions for experienced professionals globally",
        "earningsPotential": "$5,000 - $25,000+/month",
        "difficulty": "Hard",
        "rating": 4.0,
        "minPayout": "Salary",
        "paymentMethods": ["Payoneer"],
        "featured": False,
        "link": "https://crossover.com"
    },
    {
        "id": 138,
        "name": "Dribble Jobs",
        "category": "Remote Jobs",
        "description": "Remote design jobs from companies looking for creative talent",
        "earningsPotential": "$3,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://dribbble.com/jobs"
    },
    {
        "id": 139,
        "name": "Authentic Jobs",
        "category": "Remote Jobs",
        "description": "Web design and development jobs from companies with great cultures",
        "earningsPotential": "$3,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://authenticjobs.com"
    },
    {
        "id": 140,
        "name": "Lensa",
        "category": "Remote Jobs",
        "description": "AI-powered job search that matches you with remote opportunities",
        "earningsPotential": "$2,500 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "Salary",
        "paymentMethods": ["Employer Payroll"],
        "featured": False,
        "link": "https://lensa.com"
    },
    
    # ==================== GIG ECONOMY (25 platforms) ====================
    {
        "id": 141,
        "name": "TaskRabbit",
        "category": "Gig Economy",
        "description": "Get paid for local tasks like furniture assembly, moving, cleaning, and handyman work",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": True,
        "link": "https://taskrabbit.com"
    },
    {
        "id": 142,
        "name": "DoorDash",
        "category": "Gig Economy",
        "description": "Deliver food and earn tips. Flexible hours, work when you want.",
        "earningsPotential": "$500 - $3,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Fast Pay"],
        "featured": True,
        "link": "https://doordash.com/dasher"
    },
    {
        "id": 143,
        "name": "Instacart Shopper",
        "category": "Gig Economy",
        "description": "Shop and deliver groceries. Earn $17-24/hour including tips.",
        "earningsPotential": "$500 - $3,000+/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Instant Cashout"],
        "featured": True,
        "link": "https://shoppers.instacart.com"
    },
    {
        "id": 144,
        "name": "Amazon Flex",
        "category": "Gig Economy",
        "description": "Deliver Amazon packages using your own car. $18-25/hour base pay.",
        "earningsPotential": "$500 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": True,
        "link": "https://flex.amazon.com"
    },
    {
        "id": 145,
        "name": "Uber",
        "category": "Gig Economy",
        "description": "Drive passengers or deliver with Uber Eats. Flexible schedule.",
        "earningsPotential": "$500 - $4,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Instant Pay"],
        "featured": False,
        "link": "https://uber.com/drive"
    },
    {
        "id": 146,
        "name": "Lyft",
        "category": "Gig Economy",
        "description": "Rideshare driving with competitive pay and bonuses. Keep 100% of tips.",
        "earningsPotential": "$500 - $4,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Express Pay"],
        "featured": False,
        "link": "https://lyft.com/driver"
    },
    {
        "id": 147,
        "name": "Uber Eats",
        "category": "Gig Economy",
        "description": "Deliver food by car, bike, or scooter. Keep all tips.",
        "earningsPotential": "$300 - $2,500+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Instant Pay"],
        "featured": False,
        "link": "https://ubereats.com/deliver"
    },
    {
        "id": 148,
        "name": "Grubhub Driver",
        "category": "Gig Economy",
        "description": "Deliver food from local restaurants. Set your own schedule.",
        "earningsPotential": "$300 - $2,500+/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Instant Pay"],
        "featured": False,
        "link": "https://driver.grubhub.com"
    },
    {
        "id": 149,
        "name": "Shipt",
        "category": "Gig Economy",
        "description": "Shop and deliver groceries from Target, CVS, and more. $15-25/hour.",
        "earningsPotential": "$400 - $2,500+/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://shipt.com/shopper"
    },
    {
        "id": 150,
        "name": "Spark Driver (Walmart)",
        "category": "Gig Economy",
        "description": "Deliver Walmart grocery orders. $15-25/hour in most markets.",
        "earningsPotential": "$400 - $2,500+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://drive4spark.walmart.com"
    },
    {
        "id": 151,
        "name": "Roadie",
        "category": "Gig Economy",
        "description": "Deliver items of all sizes while you're already on the road. Long-distance gigs.",
        "earningsPotential": "$200 - $2,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://roadie.com"
    },
    {
        "id": 152,
        "name": "Postmates",
        "category": "Gig Economy",
        "description": "Deliver anything - food, groceries, alcohol. Now part of Uber Eats.",
        "earningsPotential": "$300 - $2,000+/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Instant Pay"],
        "featured": False,
        "link": "https://postmates.com/fleet"
    },
    {
        "id": 153,
        "name": "Rover",
        "category": "Gig Economy",
        "description": "Pet sitting, dog walking, and boarding services. Set your own rates.",
        "earningsPotential": "$300 - $3,000+/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$0",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://rover.com"
    },
    {
        "id": 154,
        "name": "Wag!",
        "category": "Gig Economy",
        "description": "Dog walking and pet care on your schedule. Background check required.",
        "earningsPotential": "$200 - $2,000+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer", "Instant Pay"],
        "featured": False,
        "link": "https://wagwalking.com"
    },
    {
        "id": 155,
        "name": "Care.com",
        "category": "Gig Economy",
        "description": "Find jobs in childcare, senior care, housekeeping, and pet care",
        "earningsPotential": "$500 - $4,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "Varies",
        "paymentMethods": ["Direct from clients"],
        "featured": False,
        "link": "https://care.com"
    },
    {
        "id": 156,
        "name": "Thumbtack",
        "category": "Gig Economy",
        "description": "Get hired for local services - photography, tutoring, home improvement",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Varies",
        "paymentMethods": ["Direct from clients"],
        "featured": False,
        "link": "https://thumbtack.com"
    },
    {
        "id": 157,
        "name": "Handy",
        "category": "Gig Economy",
        "description": "Cleaning and handyman jobs. Earn up to $22/hour for cleaning.",
        "earningsPotential": "$400 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 3.8,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://handy.com"
    },
    {
        "id": 158,
        "name": "GigSmart",
        "category": "Gig Economy",
        "description": "Find flexible shifts in warehousing, events, delivery, and more",
        "earningsPotential": "$300 - $2,500+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://gigsmart.com"
    },
    {
        "id": 159,
        "name": "Instawork",
        "category": "Gig Economy",
        "description": "Hourly work in hospitality, events, and warehouses. Get paid weekly.",
        "earningsPotential": "$400 - $3,000+/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://instawork.com"
    },
    {
        "id": 160,
        "name": "Wonolo",
        "category": "Gig Economy",
        "description": "Same-day job app for warehouse, delivery, and event work",
        "earningsPotential": "$300 - $2,500+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://wonolo.com"
    },
    {
        "id": 161,
        "name": "Field Agent",
        "category": "Gig Economy",
        "description": "Complete mystery shopping and audits at local stores. $3-15 per task.",
        "earningsPotential": "$100 - $500+/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://fieldagent.net"
    },
    {
        "id": 162,
        "name": "Gigwalk",
        "category": "Gig Economy",
        "description": "Get paid for taking photos and verifying products in stores",
        "earningsPotential": "$100 - $400+/month",
        "difficulty": "Easy",
        "rating": 3.8,
        "minPayout": "$10",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://gigwalk.com"
    },
    {
        "id": 163,
        "name": "Steady",
        "category": "Gig Economy",
        "description": "Find gig work and side hustles tailored to your skills and schedule",
        "earningsPotential": "Varies",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "Varies",
        "paymentMethods": ["Varies by gig"],
        "featured": False,
        "link": "https://steadyapp.com"
    },
    {
        "id": 164,
        "name": "Honeygain",
        "category": "Gig Economy",
        "description": "Earn passive income by sharing your unused internet bandwidth",
        "earningsPotential": "$15 - $45/month",
        "difficulty": "Easy",
        "rating": 3.7,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Bitcoin"],
        "featured": False,
        "link": "https://honeygain.com"
    },
    {
        "id": 165,
        "name": "Data Annotation Tech",
        "category": "Gig Economy",
        "description": "Train AI by labeling data, reviewing content, and completing tasks",
        "earningsPotential": "$200 - $2,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://dataannotation.tech"
    },
    # ==================== NEW PLATFORMS 166-199 ====================
    {
        "id": 166,
        "name": "Cambly",
        "category": "Teaching & Tutoring",
        "description": "Chat with English learners worldwide via video. No lesson plans required - just have conversations. Flexible scheduling with students from 130+ countries. Perfect for native speakers wanting casual teaching.",
        "earningsPotential": "$400 - $1,200/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$20",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://cambly.com"
    },
    {
        "id": 167,
        "name": "Outlier AI",
        "category": "Gig Economy",
        "description": "Train next-generation AI models by providing expert feedback on responses. High pay for specialists in coding, writing, math, and science. Remote work with flexible hours.",
        "earningsPotential": "$500 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "Weekly payout",
        "paymentMethods": ["Bank Transfer", "PayPal"],
        "featured": True,
        "link": "https://outlier.ai"
    },
    {
        "id": 168,
        "name": "Printful",
        "category": "E-commerce",
        "description": "Print-on-demand dropshipping service. Design custom products - t-shirts, mugs, posters - and sell without holding inventory. Integrates with Etsy, Shopify, and major marketplaces.",
        "earningsPotential": "$200 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "Varies by platform",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://printful.com"
    },
    {
        "id": 169,
        "name": "Respondent",
        "category": "Surveys & Research",
        "description": "High-paying research studies for professionals. Participate in interviews, focus groups, and surveys. Studies pay $75-400+ per hour. Requires professional background verification.",
        "earningsPotential": "$200 - $1,500/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "$1",
        "paymentMethods": ["PayPal"],
        "featured": True,
        "link": "https://respondent.io"
    },
    {
        "id": 170,
        "name": "Tandem",
        "category": "Teaching & Tutoring",
        "description": "Language exchange app where you can become a paid tutor. Help learners practice conversational skills while earning. Set your own rates and schedule video lessons.",
        "earningsPotential": "$300 - $1,000/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://tandem.net"
    },
    {
        "id": 171,
        "name": "Spreadshirt",
        "category": "E-commerce",
        "description": "Create and sell custom merchandise with zero upfront costs. Design t-shirts, accessories, and home decor. Earn commissions on every sale from your personal shop.",
        "earningsPotential": "$100 - $2,000/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://spreadshirt.com"
    },
    {
        "id": 172,
        "name": "Toptal",
        "category": "Freelancing",
        "description": "Elite freelance network for top 3% of talent. High-paying projects in software development, design, and finance. Rigorous screening process but exceptional rates for those accepted.",
        "earningsPotential": "$5,000 - $20,000+/month",
        "difficulty": "Hard",
        "rating": 4.7,
        "minPayout": "Bi-weekly",
        "paymentMethods": ["Bank Transfer", "Payoneer"],
        "featured": True,
        "link": "https://toptal.com"
    },
    {
        "id": 173,
        "name": "Yuno Surveys",
        "category": "Surveys & Research",
        "description": "Quick surveys with instant PayPal cashouts. No minimum threshold - get paid immediately upon completion. Simple interface with regular survey opportunities.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$0 (instant)",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://yunosurveys.com"
    },
    {
        "id": 174,
        "name": "Cloudworkers",
        "category": "Remote Jobs",
        "description": "Work as a chat moderator for various online platforms. Respond to messages, moderate communities, and provide customer support. Fully remote with flexible shifts.",
        "earningsPotential": "$400 - $1,500/month",
        "difficulty": "Easy",
        "rating": 3.8,
        "minPayout": "Monthly",
        "paymentMethods": ["Bank Transfer", "PayPal"],
        "featured": False,
        "link": "https://cloudworkers.company"
    },
    {
        "id": 175,
        "name": "Coinbase Earn",
        "category": "Trading & Investing",
        "description": "Earn free cryptocurrency by learning about blockchain projects. Watch short videos, complete quizzes, and receive crypto rewards. Great way to build a portfolio without investing.",
        "earningsPotential": "$20 - $100/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$0",
        "paymentMethods": ["Cryptocurrency"],
        "featured": False,
        "link": "https://coinbase.com/earn"
    },
    {
        "id": 176,
        "name": "Speakwrite",
        "category": "Remote Jobs",
        "description": "Legal and general transcription service. Type audio files from law firms, government agencies, and businesses. Work from home with flexible scheduling. Pays per word typed.",
        "earningsPotential": "$300 - $1,200/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Check"],
        "featured": False,
        "link": "https://speakwrite.com"
    },
    {
        "id": 177,
        "name": "Slice the Pie",
        "category": "Surveys & Research",
        "description": "Get paid to review music, fashion, and commercials before they launch. Write short reviews sharing your opinions. Earnings increase as your review quality improves.",
        "earningsPotential": "$20 - $100/month",
        "difficulty": "Easy",
        "rating": 3.6,
        "minPayout": "$10",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://slicethepie.com"
    },
    {
        "id": 178,
        "name": "Thinkific",
        "category": "Teaching & Tutoring",
        "description": "Build and sell online courses with your expertise. Create video lessons, quizzes, and certificates. Keep 100% of revenue on paid plans. Ideal for subject matter experts.",
        "earningsPotential": "$500 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "Instant via Stripe",
        "paymentMethods": ["Stripe", "PayPal"],
        "featured": False,
        "link": "https://thinkific.com"
    },
    {
        "id": 179,
        "name": "Zirtual",
        "category": "Remote Jobs",
        "description": "Work as a virtual assistant for busy professionals. Handle emails, scheduling, travel booking, and research. US-based company offering full benefits for full-time positions.",
        "earningsPotential": "$1,500 - $3,000/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "Bi-weekly",
        "paymentMethods": ["Direct Deposit"],
        "featured": False,
        "link": "https://zirtual.com"
    },
    {
        "id": 180,
        "name": "Poshmark",
        "category": "E-commerce",
        "description": "Social marketplace for selling new and used fashion. List clothing, shoes, and accessories with easy photo uploads. Strong community features help drive sales.",
        "earningsPotential": "$100 - $3,000+/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$20",
        "paymentMethods": ["Direct Deposit", "Check"],
        "featured": False,
        "link": "https://poshmark.com"
    },
    {
        "id": 181,
        "name": "Speechify",
        "category": "Digital Creators/Innovators",
        "description": "Record your voice to help build text-to-speech AI. Voice actors and clear speakers can earn creating audio samples. One-time recordings generate passive royalties.",
        "earningsPotential": "$200 - $2,000+/project",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "Per project",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://speechify.com"
    },
    {
        "id": 182,
        "name": "Qmee",
        "category": "Surveys & Research",
        "description": "Browser extension that pays for searching and shopping online. Also offers paid surveys with no minimum cashout. Instant PayPal payments from $0.01.",
        "earningsPotential": "$30 - $150/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$0.01",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://qmee.com"
    },
    {
        "id": 183,
        "name": "Arc",
        "category": "Freelancing",
        "description": "Remote job marketplace for developers. Get matched with companies seeking engineering talent. Offers both freelance contracts and full-time remote positions.",
        "earningsPotential": "$4,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "Monthly",
        "paymentMethods": ["Bank Transfer", "Payoneer"],
        "featured": False,
        "link": "https://arc.dev"
    },
    {
        "id": 184,
        "name": "Vinted",
        "category": "E-commerce",
        "description": "Sell secondhand fashion with no seller fees. List clothes, shoes, and accessories for free. Popular across Europe and growing in US/UK markets.",
        "earningsPotential": "$50 - $1,500/month",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$0.50",
        "paymentMethods": ["Bank Transfer", "PayPal"],
        "featured": False,
        "link": "https://vinted.com"
    },
    {
        "id": 185,
        "name": "Attapoll",
        "category": "Surveys & Research",
        "description": "Mobile survey app with short, well-paying surveys. Clean interface with accurate time estimates. Cash out via PayPal or gift cards with low minimum.",
        "earningsPotential": "$30 - $120/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$3",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://attapoll.com"
    },
    {
        "id": 186,
        "name": "99designs",
        "category": "Freelancing",
        "description": "Design marketplace for logos, websites, and branding. Compete in contests or work directly with clients. Higher earning potential for established designers.",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://99designs.com"
    },
    {
        "id": 187,
        "name": "Public.com",
        "category": "Trading & Investing",
        "description": "Commission-free investing with social features. Invest in stocks, ETFs, and crypto. Earn free stock slices for referrals. Great for beginners building portfolios.",
        "earningsPotential": "Variable (investments)",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$1",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://public.com"
    },
    {
        "id": 188,
        "name": "Italki",
        "category": "Teaching & Tutoring",
        "description": "Teach your native language to students globally. Set your own rates and schedule. No teaching certificate required for community tutors. Professional teachers earn premium rates.",
        "earningsPotential": "$500 - $4,000/month",
        "difficulty": "Easy",
        "rating": 4.5,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Payoneer", "Bank Transfer"],
        "featured": True,
        "link": "https://italki.com"
    },
    {
        "id": 189,
        "name": "Luno",
        "category": "Trading & Investing",
        "description": "Buy, store, and earn interest on cryptocurrency. Available in 40+ countries with competitive rates. Savings wallet earns up to 7.6% APY on Bitcoin.",
        "earningsPotential": "Variable (interest + trading)",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "No minimum",
        "paymentMethods": ["Bank Transfer", "Crypto"],
        "featured": False,
        "link": "https://luno.com"
    },
    {
        "id": 190,
        "name": "Packlink",
        "category": "E-commerce",
        "description": "Compare shipping rates and print labels for your e-commerce business. Save up to 70% on shipping costs. Integrates with major selling platforms.",
        "earningsPotential": "Cost savings tool",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "N/A",
        "paymentMethods": ["Credit Card"],
        "featured": False,
        "link": "https://packlink.com"
    },
    {
        "id": 191,
        "name": "Branded Surveys",
        "category": "Surveys & Research",
        "description": "Well-established survey site with consistent opportunities. Earn points redeemable for cash and gift cards. Loyalty program increases earnings over time.",
        "earningsPotential": "$50 - $250/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Bank Transfer", "Gift Cards"],
        "featured": False,
        "link": "https://surveys.gobranded.com"
    },
    {
        "id": 192,
        "name": "Flexjobs",
        "category": "Remote Jobs",
        "description": "Curated job board for remote and flexible positions. Every listing is hand-screened for legitimacy. Subscription-based but offers quality, scam-free opportunities.",
        "earningsPotential": "$2,000 - $8,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "Per employer",
        "paymentMethods": ["Per employer"],
        "featured": True,
        "link": "https://flexjobs.com"
    },
    {
        "id": 193,
        "name": "Rumble",
        "category": "Digital Creators/Innovators",
        "description": "Video platform alternative to YouTube. Earn from ads with creator-friendly revenue splits. Growing audience and less restrictive content policies.",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://rumble.com"
    },
    {
        "id": 194,
        "name": "Justworks",
        "category": "Remote Jobs",
        "description": "Find freelance and contract work through this HR platform. Companies use Justworks to hire remote contractors with compliant payments and benefits.",
        "earningsPotential": "$3,000 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "Bi-weekly",
        "paymentMethods": ["Direct Deposit"],
        "featured": False,
        "link": "https://justworks.com"
    },
    {
        "id": 195,
        "name": "Freecash",
        "category": "Gig Economy",
        "description": "Earn by completing offers, surveys, and app downloads. Multiple earning methods with competitive payouts. Fast withdrawals via PayPal, crypto, or gift cards.",
        "earningsPotential": "$50 - $500/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Crypto", "Gift Cards"],
        "featured": False,
        "link": "https://freecash.com"
    },
    {
        "id": 196,
        "name": "Preply",
        "category": "Teaching & Tutoring",
        "description": "Online tutoring marketplace for languages and academic subjects. Set your own rates and build a student base. Platform handles scheduling and payments.",
        "earningsPotential": "$500 - $3,500/month",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Skrill", "Bank Transfer"],
        "featured": False,
        "link": "https://preply.com"
    },
    {
        "id": 197,
        "name": "Acorns",
        "category": "Trading & Investing",
        "description": "Micro-investing app that rounds up purchases and invests spare change. Also offers Found Money cashback from partner brands. Build wealth automatically.",
        "earningsPotential": "Variable (investments)",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$0",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://acorns.com"
    },
    {
        "id": 198,
        "name": "SameSpeak",
        "category": "Teaching & Tutoring",
        "description": "Coach English conversation skills via phone or video. Help international professionals improve business English. Native speakers earn $10+ per 30-minute session.",
        "earningsPotential": "$200 - $800/month",
        "difficulty": "Easy",
        "rating": 3.9,
        "minPayout": "$20",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://samespeak.com"
    },
    {
        "id": 199,
        "name": "ySense",
        "category": "Surveys & Research",
        "description": "Established GPT site offering surveys, offers, and tasks. Daily bonuses and activity rewards boost earnings. Trusted platform operating since 2007.",
        "earningsPotential": "$50 - $300/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Payoneer", "Gift Cards"],
        "featured": False,
        "link": "https://ysense.com"
    }
]
