categories_data = [
    {
        "id": 1,
        "name": "Freelancing",
        "description": "Offer your skills and services to clients worldwide",
        "count": 5,
        "totalOpportunities": "5M+ jobs",
        "color": "from-emerald-50 to-teal-50",
        "borderColor": "border-emerald-200",
        "textColor": "text-emerald-700"
    },
    {
        "id": 2,
        "name": "Surveys & Research",
        "description": "Share your opinions and get paid for your time",
        "count": 23,
        "totalOpportunities": "100K+ surveys",
        "color": "from-blue-50 to-cyan-50",
        "borderColor": "border-blue-200",
        "textColor": "text-blue-700"
    },
    {
        "id": 3,
        "name": "Content Creation",
        "description": "Create videos, blogs, and content for income",
        "count": 13,
        "totalOpportunities": "Unlimited opportunities",
        "color": "from-orange-50 to-amber-50",
        "borderColor": "border-orange-200",
        "textColor": "text-orange-700"
    },
    {
        "id": 4,
        "name": "Trading & Investing",
        "description": "Grow your wealth through stocks, crypto, and forex",
        "count": 1,
        "totalOpportunities": "1000+ assets",
        "color": "from-indigo-50 to-violet-50",
        "borderColor": "border-indigo-200",
        "textColor": "text-indigo-700"
    },
    {
        "id": 5,
        "name": "E-commerce",
        "description": "Sell products online through various platforms",
        "count": 2,
        "totalOpportunities": "500M+ customers",
        "color": "from-rose-50 to-pink-50",
        "borderColor": "border-rose-200",
        "textColor": "text-rose-700"
    },
    {
        "id": 6,
        "name": "Teaching & Tutoring",
        "description": "Share your knowledge and teach students online",
        "count": 2,
        "totalOpportunities": "50K+ courses",
        "color": "from-green-50 to-lime-50",
        "borderColor": "border-green-200",
        "textColor": "text-green-700"
    },
    {
        "id": 7,
        "name": "Remote Jobs",
        "description": "Find full-time or part-time remote employment",
        "count": 5,
        "totalOpportunities": "3M+ jobs",
        "color": "from-slate-50 to-gray-50",
        "borderColor": "border-slate-200",
        "textColor": "text-slate-700"
    },
    {
        "id": 8,
        "name": "Gig Economy",
        "description": "Complete short tasks and micro-jobs for quick cash",
        "count": 2,
        "totalOpportunities": "200K+ tasks",
        "color": "from-yellow-50 to-amber-50",
        "borderColor": "border-yellow-200",
        "textColor": "text-yellow-700"
    }
]

platforms_data = [
    {
        "id": 1,
        "name": "Upwork",
        "category": "Freelancing",
        "description": "Global freelancing platform connecting businesses with independent professionals",
        "earningsPotential": "$1,000 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Bank Transfer", "Payoneer"],
        "featured": True,
        "link": "https://upwork.com"
    },
    {
        "id": 2,
        "name": "Fiverr",
        "category": "Freelancing",
        "description": "Marketplace for freelance services starting at $5",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": True,
        "link": "https://fiverr.com"
    },
    {
        "id": 3,
        "name": "Swagbucks",
        "category": "Surveys & Research",
        "description": "Earn rewards for surveys, shopping, and watching videos",
        "earningsPotential": "$50 - $300/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$3",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://swagbucks.com"
    },
    {
        "id": 4,
        "name": "YouTube",
        "category": "Content Creation",
        "description": "Create and monetize video content for millions of viewers",
        "earningsPotential": "$100 - $100,000+/month",
        "difficulty": "Hard",
        "rating": 4.7,
        "minPayout": "$100",
        "paymentMethods": ["AdSense", "Bank Transfer"],
        "featured": True,
        "link": "https://youtube.com"
    },
    {
        "id": 5,
        "name": "Coinbase",
        "category": "Trading & Investing",
        "description": "Buy, sell, and trade cryptocurrencies securely",
        "earningsPotential": "Variable (High Risk)",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "No minimum",
        "paymentMethods": ["Bank Transfer", "Crypto Wallet"],
        "featured": False,
        "link": "https://coinbase.com"
    },
    {
        "id": 6,
        "name": "Amazon FBA",
        "category": "E-commerce",
        "description": "Sell products on Amazon with fulfillment by Amazon",
        "earningsPotential": "$1,000 - $50,000+/month",
        "difficulty": "Hard",
        "rating": 4.4,
        "minPayout": "Bi-weekly payouts",
        "paymentMethods": ["Bank Transfer"],
        "featured": True,
        "link": "https://sell.amazon.com"
    },
    {
        "id": 7,
        "name": "VIPKid",
        "category": "Teaching & Tutoring",
        "description": "Teach English to Chinese students online",
        "earningsPotential": "$500 - $2,000/month",
        "difficulty": "Medium",
        "rating": 4.1,
        "minPayout": "$50",
        "paymentMethods": ["Bank Transfer", "PayPal"],
        "featured": False,
        "link": "https://vipkid.com"
    },
    {
        "id": 8,
        "name": "FlexJobs",
        "category": "Remote Jobs",
        "description": "Curated remote and flexible job opportunities",
        "earningsPotential": "$2,000 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.6,
        "minPayout": "Varies by employer",
        "paymentMethods": ["Direct Deposit"],
        "featured": True,
        "link": "https://flexjobs.com"
    },
    {
        "id": 9,
        "name": "TaskRabbit",
        "category": "Gig Economy",
        "description": "Complete local tasks and errands for people in your area",
        "earningsPotential": "$300 - $2,000/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$25",
        "paymentMethods": ["Direct Deposit"],
        "featured": False,
        "link": "https://taskrabbit.com"
    },
    {
        "id": 10,
        "name": "Medium Partner Program",
        "category": "Content Creation",
        "description": "Write articles and earn based on reader engagement",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["Stripe"],
        "featured": False,
        "link": "https://medium.com"
    },
    {
        "id": 11,
        "name": "Etsy",
        "category": "E-commerce",
        "description": "Sell handmade, vintage items, and craft supplies",
        "earningsPotential": "$200 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "No minimum",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": True,
        "link": "https://etsy.com"
    },
    {
        "id": 12,
        "name": "Udemy",
        "category": "Teaching & Tutoring",
        "description": "Create and sell online courses to students worldwide",
        "earningsPotential": "$100 - $10,000+/month",
        "difficulty": "Hard",
        "rating": 4.4,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Payoneer"],
        "featured": False,
        "link": "https://udemy.com"
    },
    {
        "id": 13,
        "name": "Reed.co.uk",
        "category": "Remote Jobs",
        "description": "UK's leading job board featuring thousands of remote and work from home opportunities",
        "earningsPotential": "$1,500 - $8,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "Varies by employer",
        "paymentMethods": ["Direct Deposit"],
        "featured": True,
        "link": "https://www.reed.co.uk/jobs/remote-jobs"
    },
    {
        "id": 14,
        "name": "Indeed",
        "category": "Remote Jobs",
        "description": "World's largest job site with extensive remote work listings across all industries",
        "earningsPotential": "$2,000 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.6,
        "minPayout": "Varies by employer",
        "paymentMethods": ["Direct Deposit"],
        "featured": True,
        "link": "https://www.indeed.com/q-remote-jobs.html"
    },
    {
        "id": 15,
        "name": "SurveySpotter",
        "category": "Surveys & Research",
        "description": "UK platform matching users with top survey companies. Earn up to £25 per survey",
        "earningsPotential": "$100 - $400/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "Varies by survey panel",
        "paymentMethods": ["PayPal", "Gift Cards", "Vouchers"],
        "featured": False,
        "link": "https://www.surveyspotter.com"
    },
    {
        "id": 16,
        "name": "Ipsos iSay",
        "category": "Surveys & Research",
        "description": "Earn points for sharing opinions. 100 points = $1. Redeem for cash or gift cards",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Amazon", "Walmart", "Starbucks Gift Cards"],
        "featured": False,
        "link": "https://www.ipsosisay.com"
    },
    {
        "id": 17,
        "name": "YouGov",
        "category": "Surveys & Research",
        "description": "Leading international survey panel. Earn points redeemable for cash and gift cards",
        "earningsPotential": "$30 - $150/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$15",
        "paymentMethods": ["PayPal", "Bank Transfer", "Gift Cards", "Prepaid VISA"],
        "featured": True,
        "link": "https://account.yougov.com/gb-en/join/main"
    },
    {
        "id": 18,
        "name": "Y Live Community",
        "category": "Surveys & Research",
        "description": "UK survey panel paying £1 per 5 minutes. Focus on business, culture, and politics",
        "earningsPotential": "$60 - $250/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "£50",
        "paymentMethods": ["Bank Transfer"],
        "featured": False,
        "link": "https://www.ylive-community.com"
    },
    {
        "id": 19,
        "name": "Google Opinion Rewards",
        "category": "Surveys & Research",
        "description": "Mobile app for quick surveys. Earn $0.10-$1 per survey. Android: Play credit, iOS: PayPal cash",
        "earningsPotential": "$30 - $100/year",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "$2",
        "paymentMethods": ["PayPal (iOS)", "Google Play Credit (Android)"],
        "featured": False,
        "link": "https://surveys.google.com/google-opinion-rewards/"
    },
    {
        "id": 20,
        "name": "Qmee",
        "category": "Surveys & Research",
        "description": "Earn cash from surveys, shopping cashback, and search rewards. Instant payout with no minimum",
        "earningsPotential": "$50 - $150/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "No minimum",
        "paymentMethods": ["PayPal", "Venmo", "Gift Cards"],
        "featured": True,
        "link": "https://www.qmee.com/en-gb"
    },
    # Additional Surveys & Research Platforms (21-37)
    {
        "id": 21,
        "name": "Prolific",
        "category": "Surveys & Research",
        "description": "Academic research platform paying fair rates for quality survey participation. Known for higher payouts than traditional survey sites, with studies from universities and research institutions worldwide. Average earnings of $6-12 per hour make this one of the most lucrative survey platforms available.",
        "earningsPotential": "$100 - $500/month",
        "difficulty": "Easy",
        "rating": 4.8,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Circle"],
        "featured": True,
        "link": "https://www.prolific.co"
    },
    {
        "id": 22,
        "name": "Toluna",
        "category": "Surveys & Research",
        "description": "Global survey community with over 21 million members. Participate in surveys, polls, and product testing opportunities. Points can be redeemed for cash, gift cards, or sweepstakes entries. Regular survey invitations and a user-friendly mobile app make earning convenient.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Gift Cards", "Vouchers"],
        "featured": False,
        "link": "https://www.toluna.com"
    },
    {
        "id": 23,
        "name": "LifePoints",
        "category": "Surveys & Research",
        "description": "Established survey panel by Lightspeed offering points for completing surveys about products and services. Surveys typically take 10-20 minutes and cover topics from consumer goods to healthcare. Points convert to PayPal cash or popular gift cards.",
        "earningsPotential": "$40 - $150/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://www.lifepointspanel.com"
    },
    {
        "id": 24,
        "name": "Branded Surveys",
        "category": "Surveys & Research",
        "description": "Fast-growing survey platform offering competitive payouts and frequent survey opportunities. Features a loyalty program with bonus points for consistent participation. Daily polls and quick surveys supplement regular longer studies. Clean interface with reliable payments.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Bank Transfer", "Gift Cards"],
        "featured": False,
        "link": "https://surveys.gobranded.com"
    },
    {
        "id": 25,
        "name": "Opinion Outpost",
        "category": "Surveys & Research",
        "description": "Survey panel connecting consumers with market research companies. Earn points for sharing opinions on products, services, and advertising. Quarterly prize draws offer additional earning potential. Low payout threshold makes cashing out quick and easy.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Amazon Gift Cards"],
        "featured": False,
        "link": "https://www.opinionoutpost.com"
    },
    {
        "id": 26,
        "name": "Pinecone Research",
        "category": "Surveys & Research",
        "description": "Exclusive, invitation-only survey panel known for consistent survey availability and reliable payments. Each survey pays a flat $3 rate, making earnings predictable. Product testing opportunities provide additional income and free products to try.",
        "earningsPotential": "$30 - $90/month",
        "difficulty": "Easy",
        "rating": 4.5,
        "minPayout": "$3",
        "paymentMethods": ["PayPal", "Check", "Gift Cards"],
        "featured": True,
        "link": "https://www.pineconeresearch.com"
    },
    {
        "id": 27,
        "name": "Survey Junkie",
        "category": "Surveys & Research",
        "description": "One of the most popular survey sites with over 10 million members. User-friendly platform offering surveys matched to your profile. Points are worth $0.01 each, with most surveys paying 50-200 points. Consistent survey availability and fast payments.",
        "earningsPotential": "$40 - $150/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Bank Transfer", "Gift Cards"],
        "featured": True,
        "link": "https://www.surveyjunkie.com"
    },
    {
        "id": 28,
        "name": "InboxDollars",
        "category": "Surveys & Research",
        "description": "Multi-earning platform combining surveys with cashback shopping, video watching, and game playing. $5 signup bonus for new members. Surveys pay actual cash amounts rather than points, making earnings transparent. Owned by Prodege, a trusted name in rewards.",
        "earningsPotential": "$50 - $200/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$15",
        "paymentMethods": ["PayPal", "Gift Cards", "Check"],
        "featured": False,
        "link": "https://www.inboxdollars.com"
    },
    {
        "id": 29,
        "name": "MyPoints",
        "category": "Surveys & Research",
        "description": "Rewards program offering points for surveys, shopping, watching videos, and reading emails. Partnership with major retailers provides excellent cashback opportunities. Points convert to travel miles, gift cards, or PayPal cash. Long-standing reputation since 1996.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Gift Cards", "Travel Miles"],
        "featured": False,
        "link": "https://www.mypoints.com"
    },
    {
        "id": 30,
        "name": "PrizeRebel",
        "category": "Surveys & Research",
        "description": "GPT (Get-Paid-To) site offering surveys, offers, tasks, and videos. Tiered membership system rewards loyal users with bonuses up to 30%. Daily challenges and contests add extra earning opportunities. Over $20 million paid out to members worldwide.",
        "earningsPotential": "$50 - $250/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$2",
        "paymentMethods": ["PayPal", "Bitcoin", "Gift Cards"],
        "featured": False,
        "link": "https://www.prizerebel.com"
    },
    {
        "id": 31,
        "name": "Valued Opinions",
        "category": "Surveys & Research",
        "description": "Premium survey panel focusing on quality over quantity. Surveys typically pay $1-5 each and cover consumer products, media, and lifestyle topics. Rewards redeemable for major retail gift cards. Professional interface with reliable survey matching.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$10",
        "paymentMethods": ["Gift Cards", "Vouchers"],
        "featured": False,
        "link": "https://www.valuedopinions.co.uk"
    },
    {
        "id": 32,
        "name": "Forthright",
        "category": "Surveys & Research",
        "description": "Modern survey platform offering instant PayPal payments upon survey completion. No point systems or minimum thresholds—get paid immediately. Surveys focus on consumer research and pay competitive rates. Clean, mobile-optimized experience.",
        "earningsPotential": "$40 - $120/month",
        "difficulty": "Easy",
        "rating": 4.3,
        "minPayout": "No minimum",
        "paymentMethods": ["PayPal"],
        "featured": False,
        "link": "https://www.forthright.com"
    },
    {
        "id": 33,
        "name": "Attapoll",
        "category": "Surveys & Research",
        "description": "Mobile-first survey app with a clean interface and frequent survey opportunities. Low $3 payout threshold makes cashing out quick. Surveys are well-matched to user profiles, reducing disqualification rates. Available on iOS and Android.",
        "earningsPotential": "$20 - $80/month",
        "difficulty": "Easy",
        "rating": 4.2,
        "minPayout": "$3",
        "paymentMethods": ["PayPal", "Revolut", "Charity Donation"],
        "featured": False,
        "link": "https://attapoll.app"
    },
    # Additional Content Creation Platforms (34-45)
    {
        "id": 34,
        "name": "Twitch",
        "category": "Content Creation",
        "description": "Leading live streaming platform for gamers and creative content creators. Monetize through subscriptions, bits, ads, and sponsorships. Build a community while streaming games, music, art, or just chatting. Partner program offers enhanced revenue sharing.",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Hard",
        "rating": 4.5,
        "minPayout": "$50",
        "paymentMethods": ["Bank Transfer", "PayPal", "Check"],
        "featured": True,
        "link": "https://www.twitch.tv"
    },
    {
        "id": 35,
        "name": "TikTok Creator Fund",
        "category": "Content Creation",
        "description": "Earn money creating short-form video content on the world's fastest-growing social platform. Creator Fund pays based on video views and engagement. Additional income through brand partnerships, gifts, and the Creator Marketplace.",
        "earningsPotential": "$50 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Zelle"],
        "featured": True,
        "link": "https://www.tiktok.com/creators"
    },
    {
        "id": 36,
        "name": "Substack",
        "category": "Content Creation",
        "description": "Newsletter platform allowing writers to build paid subscriber bases. Keep 90% of subscription revenue. Perfect for journalists, experts, and thought leaders. Built-in audience discovery and simple payment processing.",
        "earningsPotential": "$100 - $50,000+/month",
        "difficulty": "Medium",
        "rating": 4.6,
        "minPayout": "$10",
        "paymentMethods": ["Stripe", "Bank Transfer"],
        "featured": False,
        "link": "https://substack.com"
    },
    {
        "id": 37,
        "name": "Patreon",
        "category": "Content Creation",
        "description": "Membership platform for creators to earn recurring income from fans. Offer exclusive content, community access, and perks to patrons. Used by artists, podcasters, writers, and educators. Flexible tier pricing and creator-friendly terms.",
        "earningsPotential": "$100 - $100,000+/month",
        "difficulty": "Medium",
        "rating": 4.5,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Payoneer", "Bank Transfer"],
        "featured": True,
        "link": "https://www.patreon.com"
    },
    {
        "id": 38,
        "name": "Spotify for Podcasters",
        "category": "Content Creation",
        "description": "Create and monetize podcasts on the world's largest audio streaming platform. Earn through listener support, ads, and paid subscriptions. Free hosting and distribution to all major podcast platforms. Analytics help grow your audience.",
        "earningsPotential": "$50 - $10,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "$10",
        "paymentMethods": ["Stripe"],
        "featured": False,
        "link": "https://podcasters.spotify.com"
    },
    {
        "id": 39,
        "name": "Shutterstock Contributor",
        "category": "Content Creation",
        "description": "Sell your photos, videos, and illustrations to a global marketplace. Earn royalties each time your content is downloaded. Over 2 million customers including major brands and media companies. Passive income potential from a quality portfolio.",
        "earningsPotential": "$50 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "$35",
        "paymentMethods": ["PayPal", "Payoneer", "Skrill"],
        "featured": False,
        "link": "https://submit.shutterstock.com"
    },
    {
        "id": 40,
        "name": "Adobe Stock Contributor",
        "category": "Content Creation",
        "description": "Sell creative assets including photos, vectors, illustrations, and videos. Integration with Adobe Creative Cloud means massive exposure to professional designers. Competitive royalty rates of 33% for photos and up to 35% for videos.",
        "earningsPotential": "$50 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$25",
        "paymentMethods": ["PayPal", "Skrill"],
        "featured": False,
        "link": "https://contributor.stock.adobe.com"
    },
    {
        "id": 41,
        "name": "Ko-fi",
        "category": "Content Creation",
        "description": "Accept donations, sell products, and offer memberships with 0% platform fees on donations. Perfect for artists, writers, and small creators. Simple setup with no minimum payout. Shop feature allows selling digital products and commissions.",
        "earningsPotential": "$20 - $5,000+/month",
        "difficulty": "Easy",
        "rating": 4.4,
        "minPayout": "No minimum",
        "paymentMethods": ["PayPal", "Stripe"],
        "featured": False,
        "link": "https://ko-fi.com"
    },
    {
        "id": 42,
        "name": "Gumroad",
        "category": "Content Creation",
        "description": "Sell digital products directly to your audience with simple e-commerce tools. Popular for ebooks, courses, music, and software. Flat 10% fee keeps pricing simple. Built-in audience features help creators grow their following.",
        "earningsPotential": "$100 - $20,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Bank Transfer", "Stripe"],
        "featured": False,
        "link": "https://gumroad.com"
    },
    {
        "id": 43,
        "name": "Redbubble",
        "category": "Content Creation",
        "description": "Upload artwork and have it printed on products like t-shirts, stickers, and phone cases. No inventory or shipping to manage—Redbubble handles everything. Set your own margins on top of base prices. Global marketplace with millions of buyers.",
        "earningsPotential": "$50 - $2,000+/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$20",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://www.redbubble.com"
    },
    {
        "id": 44,
        "name": "Envato Elements Contributor",
        "category": "Content Creation",
        "description": "Sell premium digital assets including templates, graphics, audio, and video. Access to Envato's massive customer base of creative professionals. Monthly subscriber earnings based on download frequency. High-quality standards ensure premium pricing.",
        "earningsPotential": "$100 - $5,000+/month",
        "difficulty": "Hard",
        "rating": 4.2,
        "minPayout": "$50",
        "paymentMethods": ["PayPal", "Payoneer", "Skrill", "Bank Transfer"],
        "featured": False,
        "link": "https://elements.envato.com/authors"
    },
    {
        "id": 45,
        "name": "Skillshare Teacher",
        "category": "Content Creation",
        "description": "Create video classes and earn royalties based on minutes watched. Topics range from design and photography to business and lifestyle. Community of 12+ million learners actively seeking new skills. Referral bonuses for bringing new students.",
        "earningsPotential": "$100 - $3,000+/month",
        "difficulty": "Medium",
        "rating": 4.3,
        "minPayout": "$10",
        "paymentMethods": ["PayPal", "Payoneer"],
        "featured": False,
        "link": "https://www.skillshare.com/teach"
    },
    # Additional Freelancing Platforms (46-48)
    {
        "id": 46,
        "name": "Toptal",
        "category": "Freelancing",
        "description": "Elite freelance network for top 3% of talent in software development, design, and finance. Rigorous screening process ensures high-quality clients and premium rates. Long-term engagements with Fortune 500 companies and funded startups. Excellent for experienced professionals.",
        "earningsPotential": "$5,000 - $20,000+/month",
        "difficulty": "Hard",
        "rating": 4.7,
        "minPayout": "Weekly payouts",
        "paymentMethods": ["Bank Transfer", "Payoneer"],
        "featured": True,
        "link": "https://www.toptal.com"
    },
    {
        "id": 47,
        "name": "Freelancer.com",
        "category": "Freelancing",
        "description": "Global freelancing marketplace with over 60 million users. Compete for projects in web development, writing, design, data entry, and more. Milestone payment system protects both freelancers and clients. Free membership with optional upgrades.",
        "earningsPotential": "$500 - $5,000+/month",
        "difficulty": "Medium",
        "rating": 4.0,
        "minPayout": "$30",
        "paymentMethods": ["PayPal", "Bank Transfer", "Skrill"],
        "featured": False,
        "link": "https://www.freelancer.com"
    },
    {
        "id": 48,
        "name": "PeoplePerHour",
        "category": "Freelancing",
        "description": "UK-based freelance platform connecting businesses with skilled professionals. Offers fixed-price projects and hourly work. AI-powered matching system finds relevant opportunities. Escrow payment protection and dispute resolution ensure fair transactions.",
        "earningsPotential": "$1,000 - $8,000+/month",
        "difficulty": "Medium",
        "rating": 4.2,
        "minPayout": "£50",
        "paymentMethods": ["PayPal", "Bank Transfer"],
        "featured": False,
        "link": "https://www.peopleperhour.com"
    },
    # Additional Remote Jobs Platforms (49-50)
    {
        "id": 49,
        "name": "We Work Remotely",
        "category": "Remote Jobs",
        "description": "Largest remote work community with 3+ million monthly visitors. Quality job listings from companies like Google, Amazon, and Basecamp. Categories include programming, design, customer support, and management. No account needed to browse and apply.",
        "earningsPotential": "$3,000 - $15,000+/month",
        "difficulty": "Medium",
        "rating": 4.6,
        "minPayout": "Varies by employer",
        "paymentMethods": ["Direct Deposit"],
        "featured": True,
        "link": "https://weworkremotely.com"
    },
    {
        "id": 50,
        "name": "Remote OK",
        "category": "Remote Jobs",
        "description": "Aggregator of remote job opportunities updated daily. Filter by salary, location, and job type. Salary statistics help negotiate fair compensation. Free job alerts notify you of matching positions instantly.",
        "earningsPotential": "$2,500 - $12,000+/month",
        "difficulty": "Medium",
        "rating": 4.4,
        "minPayout": "Varies by employer",
        "paymentMethods": ["Direct Deposit"],
        "featured": False,
        "link": "https://remoteok.com"
    },
    # Additional Gig Economy Platform (51)
    {
        "id": 51,
        "name": "Instacart Shopper",
        "category": "Gig Economy",
        "description": "Shop and deliver groceries for customers in your area. Flexible hours with instant cashout available. Earn through batch payments plus tips. Full-service shoppers handle shopping and delivery while in-store shoppers focus on picking orders.",
        "earningsPotential": "$500 - $2,500/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "Instant cashout available",
        "paymentMethods": ["Direct Deposit", "Instant Cashout"],
        "featured": False,
        "link": "https://shoppers.instacart.com"
    },
    # Additional Survey Platforms to reach 23 (52-53)
    {
        "id": 52,
        "name": "Panel Station",
        "category": "Surveys & Research",
        "description": "International survey panel operating in over 40 countries. Earn points for surveys and redeem for PayPal cash or gift cards. Mobile app allows earning on the go. Regular surveys with good qualification rates.",
        "earningsPotential": "$30 - $100/month",
        "difficulty": "Easy",
        "rating": 4.0,
        "minPayout": "$5",
        "paymentMethods": ["PayPal", "Gift Cards"],
        "featured": False,
        "link": "https://www.thepanelstation.com"
    },
    {
        "id": 53,
        "name": "Crowdtap",
        "category": "Surveys & Research",
        "description": "Influence brands by sharing opinions and testing products. Earn points for quick surveys and product missions. Rewards include gift cards to popular retailers. Mobile-friendly platform with engaging, bite-sized activities.",
        "earningsPotential": "$20 - $80/month",
        "difficulty": "Easy",
        "rating": 4.1,
        "minPayout": "$10",
        "paymentMethods": ["Gift Cards"],
        "featured": False,
        "link": "https://www.crowdtap.com"
    }
]