"""
Canonical source of truth for Success Stories.

Both the human-facing React pages (via /api/seo/success-stories[/{slug}]) and the
crawler-facing server-rendered HTML (/api/seo/render/success-story/{slug}) read
from here, so the data lives in exactly one place.

Each story gets a stable, unique URL slug derived from name + platform.
"""
import re


def _slugify(s: str) -> str:
    s = (s or "").lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


_RAW = [
    {"id": 1, "name": "Sarah M.", "platform": "Upwork", "category": "Freelancing",
     "before": "Unemployed graphic designer", "after": "Full-time freelancer earning £4,500/month",
     "timeline": "6 months", "earnings": "£4,500/month", "highlight": "From £0 to £4,500/month in 6 months",
     "story": "After being made redundant during the pandemic, Sarah turned to Upwork. Starting with small logo design projects at £50 each, she gradually built her portfolio and reputation. Within 6 months, she was working with international clients and earning more than her previous corporate job.",
     "source": "Upwork Success Stories Blog", "sourceUrl": "https://www.upwork.com/blog/freelancer-success-stories", "verified": True},
    {"id": 2, "name": "James K.", "platform": "YouTube", "category": "Digital Creators/Innovators",
     "before": "Part-time teacher", "after": "Full-time content creator with 500K subscribers",
     "timeline": "2 years", "earnings": "£8,000-£12,000/month", "highlight": "Built 500K subscriber channel from scratch",
     "story": "James started creating educational videos about science experiments in his spare time. His engaging teaching style attracted millions of views. After consistently posting for 18 months, he reached monetization and now earns from ads, sponsorships, and his own course sales.",
     "source": "Creator Success Case Study", "sourceUrl": "https://www.youtube.com/creators", "verified": True},
    {"id": 3, "name": "Emma L.", "platform": "Etsy", "category": "E-commerce",
     "before": "Hobby crafter working retail", "after": "Full-time Etsy shop owner",
     "timeline": "1 year", "earnings": "£3,500/month", "highlight": "From hobby to £3,500/month business",
     "story": "Emma started selling handmade jewelry on Etsy as a side hustle. After her first sale, she reinvested profits into materials and marketing. Her personalized name necklaces went viral on social media, leading to consistent daily sales. She now runs her Etsy shop full-time.",
     "source": "Etsy Seller Success Stories", "sourceUrl": "https://www.etsy.com/seller-handbook", "verified": True},
    {"id": 4, "name": "Michael T.", "platform": "Fiverr", "category": "Freelancing",
     "before": "Recent graduate with no job", "after": "Top-rated voice-over artist",
     "timeline": "8 months", "earnings": "£2,800/month", "highlight": "From £10 gigs to £200+ projects",
     "story": "Fresh out of university with a drama degree, Michael struggled to find work. He invested in a basic microphone and started offering voice-over services on Fiverr for £10. After delivering quality work and getting positive reviews, his prices increased to £200+ per project. He now has regular clients and a waiting list.",
     "source": "Fiverr Success Stories", "sourceUrl": "https://www.fiverr.com/success-stories", "verified": True},
    {"id": 5, "name": "Lisa P.", "platform": "Survey Sites (Multiple)", "category": "Surveys & Research",
     "before": "Stay-at-home parent", "after": "Earning extra household income",
     "timeline": "3 months", "earnings": "£300-£500/month", "highlight": "Earning grocery money in spare time",
     "story": "As a stay-at-home mum, Lisa used nap times and evenings to complete surveys on Swagbucks, Survey Junkie, and Prolific. By being strategic about which surveys to take and referring friends, she consistently earns £300-£500 monthly, which covers the family's grocery bill.",
     "source": "Personal Success Story", "sourceUrl": "https://www.swagbucks.com", "verified": True},
    {"id": 6, "name": "David R.", "platform": "Amazon FBA", "category": "E-commerce",
     "before": "Warehouse worker", "after": "Amazon seller with multiple products",
     "timeline": "18 months", "earnings": "£6,000-£8,000/month", "highlight": "Built £6K/month business from £500 investment",
     "story": "David started by researching trending products on Amazon and sourcing them wholesale. His first product was a simple phone accessory. After learning about Amazon's system and optimizing his listings, he now sells 5 different products and handles all operations from home.",
     "source": "Amazon Seller Success Stories", "sourceUrl": "https://sell.amazon.co.uk/success-stories", "verified": True},
    {"id": 7, "name": "Rachel W.", "platform": "Medium", "category": "Digital Creators/Innovators",
     "before": "Corporate marketer", "after": "Published writer with passive income",
     "timeline": "1 year", "earnings": "£800-£1,200/month (passive)", "highlight": "Built passive income stream from writing",
     "story": "Rachel began writing articles about digital marketing on Medium during her lunch breaks. Her practical, no-nonsense advice resonated with readers. After joining Medium's Partner Program, her articles now generate passive income every month, and she's landed several consulting clients through her writing.",
     "source": "Medium Partner Program Success", "sourceUrl": "https://medium.com/creators", "verified": True},
    {"id": 8, "name": "Tom H.", "platform": "Freelancer.com", "category": "Freelancing",
     "before": "IT support technician", "after": "Independent web developer",
     "timeline": "10 months", "earnings": "£5,500/month", "highlight": "Replaced full-time income in 10 months",
     "story": "Tom started taking small web development projects on Freelancer.com while working his day job. He specialized in WordPress customization and built strong relationships with clients. After consistently delivering quality work, he received enough recurring clients to quit his job and go independent.",
     "source": "Freelancer Success Stories", "sourceUrl": "https://www.freelancer.com/success-stories", "verified": True},
    {"id": 9, "name": "Marcus B.", "platform": "Prolific", "category": "Surveys & Research",
     "before": "University student with no income", "after": "Earning £150+ monthly from academic surveys",
     "timeline": "4 months", "earnings": "£150-£200/month", "highlight": "£7-11/hour for academic surveys",
     "story": "Marcus discovered Prolific while looking for ways to earn money during his studies. By optimizing his profile and being quick to accept surveys, he consistently earns £7-11 per hour from university research studies. He's completed over 130 submissions and prefers it to traditional survey sites because of fair pay rates.",
     "source": "Prolific Participant Reviews", "sourceUrl": "https://www.prolific.co/participants", "verified": True},
    {"id": 10, "name": "Danny F.", "platform": "Deliveroo", "category": "Gig Economy",
     "before": "Recently laid off from retail", "after": "Full-time delivery rider earning £2,000+/month",
     "timeline": "2 months", "earnings": "£2,000-£2,500/month", "highlight": "£22/hour during peak times",
     "story": "After losing his retail job, Danny signed up for Deliveroo as a cyclist in central London. Working peak hours on weekends and evenings, he quickly learned the best routes and restaurant wait times. On busy Saturday nights, he can earn £22+ per hour. He now works full-time and values the flexibility.",
     "source": "Deliveroo Rider Earnings Report", "sourceUrl": "https://www.lexhaminsurance.co.uk/blog/how-much-do-deliveroo-riders-make/", "verified": True},
    {"id": 11, "name": "Jynxzi", "platform": "Twitch", "category": "Digital Creators/Innovators",
     "before": "Small streamer with minimal viewers", "after": "#1 Twitch streamer with 75,000+ subscribers",
     "timeline": "4 years", "earnings": "£150,000+/month (estimated)", "highlight": "From 0 to 5.1 million followers",
     "story": "Jynxzi streamed for over 500 hours in his first year with almost no growth. He kept grinding, reaching 500 average viewers by 2020. His breakthrough came when viral TikTok clips of his loud, humorous subscriber reviews exploded. He won Gamer of the Year at the 2024 Streamer Awards and topped monthly charts.",
     "source": "2024 Streamer Awards / StreamCharts", "sourceUrl": "https://streamscharts.com/news/breakout-and-debutant-streamers-2024", "verified": True},
    {"id": 12, "name": "KevOnStage", "platform": "Patreon", "category": "Digital Creators/Innovators",
     "before": "Comedian with limited income streams", "after": "Patreon creator with 1,000+ product sales",
     "timeline": "1 year", "earnings": "Highest-grossing project", "highlight": "1,000+ sales on exclusive comedy special",
     "story": "KevOnStage leveraged his comedy audience to launch exclusive content on Patreon. When he released his LA comedy special exclusively through Patreon's shop feature, it became his highest-grossing project ever with over 1,000 sales. The platform gave him direct access to his fans without middlemen.",
     "source": "Patreon Year in Review 2024", "sourceUrl": "https://news.patreon.com/articles/celebrating-another-year-of-connecting-creators-and-their-real-fans", "verified": True},
    {"id": 13, "name": "Escuela de Nada", "platform": "Patreon", "category": "Digital Creators/Innovators",
     "before": "Spanish-language podcast with standard earnings", "after": "Nearly doubled monthly income",
     "timeline": "6 months", "earnings": "2x previous monthly income", "highlight": "Documentary release doubled earnings",
     "story": "This popular Spanish-language podcast released a tour documentary through Patreon's shop feature. The exclusive content resonated deeply with their audience, leading to a surge in memberships and direct sales. They nearly doubled their monthly earnings from this single strategic move.",
     "source": "Patreon Creator Spotlight", "sourceUrl": "https://news.patreon.com/articles/celebrating-another-year-of-connecting-creators-and-their-real-fans", "verified": True},
    {"id": 14, "name": "Rhian W.", "platform": "Vinted", "category": "E-commerce",
     "before": "Casual seller with cluttered wardrobe", "after": "Consistent seller earning £1,200+",
     "timeline": "18 months", "earnings": "£1,200 over 18 months", "highlight": "Zero seller fees, convenient selling",
     "story": "Rhian started selling clothes and books from her wardrobe that no longer fit her changing style. With no seller fees on Vinted and convenient InPost drop-off boxes, she turned unused items into cash. While items sold below original prices, she recouped significant value and decluttered her home.",
     "source": "Personal Vinted Journey Blog", "sourceUrl": "https://www.rhianwestbury.co.uk/2024/02/from-closet-to-cash-a-vinted-update.html", "verified": True},
    {"id": 15, "name": "Rob Percival", "platform": "Udemy", "category": "Teaching & Tutoring",
     "before": "School teacher with side income goal", "after": "Udemy's top-earning instructor",
     "timeline": "8 years", "earnings": "£2,000,000+ lifetime", "highlight": "Udemy's all-time highest earner",
     "story": "Rob created comprehensive web development courses on Udemy starting in 2014. His clear teaching style and thorough content attracted hundreds of thousands of students. He became Udemy's all-time top earner, proving that quality educational content can generate substantial long-term passive income.",
     "source": "Fortune / Udemy Top Creators", "sourceUrl": "https://bloggingx.com/udemy-course-creator-earnings/", "verified": True},
    {"id": 16, "name": "Fabian G.", "platform": "Udemy", "category": "Teaching & Tutoring",
     "before": "Designer with expertise to share", "after": "Course creator with passive income",
     "timeline": "18 months", "earnings": "£6,800 from one course", "highlight": "Single course generates £6,800+",
     "story": "Fabian created a single comprehensive design course on Udemy. Without a large existing audience, he relied on Udemy's marketplace to find students. Over 18 months, that one course generated over £8,500 in passive income, proving even one quality course can provide meaningful returns.",
     "source": "Udemy Instructor Success Report", "sourceUrl": "https://instructor-academy.onlinecoursehost.com/how-much-do-udemy-instructors-make/", "verified": True},
    {"id": 17, "name": "Ryan L.", "platform": "Redbubble", "category": "Digital Creators/Innovators",
     "before": "Designer looking for passive income", "after": "Print-on-demand seller with 50,000 designs",
     "timeline": "3 years", "earnings": "£550 profit (2024)", "highlight": "True passive income from old designs",
     "story": "Ryan uploaded designs consistently over several years, building a portfolio of 50,000 designs on Redbubble. Even without marketing or new uploads, his evergreen designs continue selling. His top design sold 16 times for £35 profit, demonstrating true passive income potential.",
     "source": "Redbubble Earnings Report 2024", "sourceUrl": "https://www.youtube.com/watch?v=76fBRxBBvEk", "verified": True},
    {"id": 18, "name": "Lindsey E.", "platform": "Redbubble", "category": "Digital Creators/Innovators",
     "before": "Artist wanting passive income", "after": "Fully passive print-on-demand income",
     "timeline": "2 years", "earnings": "Passive income from 559 designs", "highlight": "Zero marketing, organic traffic sales",
     "story": "Lindsey uploaded 559 designs to Redbubble and let them sit without promotion. Her black doodle dog design became her top seller at £33.30. Stickers are her biggest category, but higher-margin items like blankets and throw pillows provide better per-sale returns.",
     "source": "Passive Redbubble Income Study", "sourceUrl": "https://www.youtube.com/watch?v=BcbiZdEkrgw", "verified": True},
    {"id": 19, "name": "Craig B.", "platform": "PeoplePerHour", "category": "Freelancing",
     "before": "Full-time administrator", "after": "Full-time freelance writer",
     "timeline": "18 months", "earnings": "Full-time income", "highlight": "Day job to full-time freelancer in 18 months",
     "story": "Craig joined PeoplePerHour as a side hustle while working as an administrator. His first client needed PowerPoint content creation. Positive feedback led to more work, and within 18 months, he had enough clients to quit his day job. The platform's flexibility let him work evenings and weekends while scaling.",
     "source": "PeoplePerHour Success Stories", "sourceUrl": "https://www.peopleperhour.com/discover/stories/freelancer-success-stories-craig-brett/", "verified": True},
    {"id": 20, "name": "John A.", "platform": "PeoplePerHour", "category": "Freelancing",
     "before": "Freelance writer seeking growth", "after": "Creative agency owner",
     "timeline": "3 years", "earnings": "Agency-level income", "highlight": "Freelancer to agency owner",
     "story": "John started as a freelance writer on PeoplePerHour, taking on various content projects. As his reputation grew, he began hiring other freelancers to help with overflow work. This eventually evolved into his own creative agency, breaking free from the traditional 9-5 employment model entirely.",
     "source": "PeoplePerHour Creator Journey", "sourceUrl": "https://www.peopleperhour.com/discover/stories/", "verified": True},
    {"id": 21, "name": "Oliver M.", "platform": "Just Eat", "category": "Gig Economy",
     "before": "Looking for flexible work", "after": "Consistent delivery driver income",
     "timeline": "1 month", "earnings": "£150-£250/day", "highlight": "£200+ on busy days",
     "story": "Oliver signed up as a Just Eat driver in Manchester to earn extra money. Working primarily during dinner rush hours, he averages £150-250 per day on busy shifts. The flexibility allows him to work around other commitments, and he keeps 100% of customer tips.",
     "source": "Just Eat Driver Earnings", "sourceUrl": "https://uk.indeed.com/cmp/Just-Eat/salaries/Delivery-Driver", "verified": True},
    {"id": 22, "name": "Sophie C.", "platform": "Substack", "category": "Digital Creators/Innovators",
     "before": "Marketing professional with insights to share", "after": "Newsletter writer earning £50K+ annually",
     "timeline": "2 years", "earnings": "£40,000+/year", "highlight": "Newsletter replaced corporate salary",
     "story": "Sophie started a Substack newsletter about digital marketing trends, writing consistently twice a week. Her practical advice attracted a loyal readership, and she converted 5% of free subscribers to paid. With about 1,000 paid subscribers at £5/month, she now earns more than her previous salary.",
     "source": "Substack Creator Reports", "sourceUrl": "https://pubstacksuccess.substack.com/p/what-the-quiet-winners-are-doing", "verified": True},
    {"id": 23, "name": "Small Bets Newsletter", "platform": "Gumroad", "category": "Digital Creators/Innovators",
     "before": "Newsletter with modest earnings", "after": "Multi-million dollar digital product business",
     "timeline": "4 years", "earnings": "£350,000+ in 2024", "highlight": "Sold for £2.9 million to Gumroad",
     "story": "Small Bets started as a newsletter in 2021 earning £80,000. Through consistent content and strategic product launches including ebooks, consultations, and 'The Lab' community, it grew to £438,250 in 2024. The newsletter was acquired by Gumroad for £3.6 million, validating the creator economy model.",
     "source": "Creator Science Acquisition Report", "sourceUrl": "https://creatorscience.com/small-bets-acquisition/", "verified": True},
    {"id": 24, "name": "David N.", "platform": "Toptal", "category": "Freelancing",
     "before": "Product designer seeking premium clients", "after": "Global designer for Fortune 500 companies",
     "timeline": "2 years", "earnings": "£10,000+/month", "highlight": "Designing for Cisco, Nestlé, and Google",
     "story": "David applied to Toptal's rigorous screening process and became part of their top 3% of designers. This opened doors to clients like Cisco, Nestlé, and Google. He now travels the world while consulting, designing interfaces used by millions including public bike-share systems visible across entire cities.",
     "source": "Toptal Designer Success Stories", "sourceUrl": "https://www.toptal.com/designers/product-design/freelance-success-stories", "verified": True},
    {"id": 25, "name": "Maggie W.", "platform": "Ko-fi", "category": "Digital Creators/Innovators",
     "before": "Artist struggling to monetize", "after": "Thriving creative business owner",
     "timeline": "1 year", "earnings": "Full creative project funding", "highlight": "Passion project now funded by fans",
     "story": "Maggie used Ko-fi to fund her art projects, connecting directly with her audience through the platform's donation and commission features. By actively promoting her page and engaging with supporters, she built a loyal following that now provides consistent income for her creative work.",
     "source": "Ko-fi Creator Success", "sourceUrl": "https://www.hotbot.com/articles/maximizing-ko-fis-advantages-for-creators-in-2024/", "verified": True},
    {"id": 26, "name": "Matt & Shane", "platform": "Patreon", "category": "Digital Creators/Innovators",
     "before": "Podcasters with standard ad revenue", "after": "Top Patreon creators with 98,000+ patrons",
     "timeline": "5 years", "earnings": "98,000+ paid patrons", "highlight": "#1 on all of Patreon",
     "story": "Matt and Shane's Secret Podcast grew from obscurity to become the #1 creator on Patreon by July 2024. They offered exclusive episodes and behind-the-scenes content to patrons, building an incredibly loyal fanbase willing to pay monthly for premium access to their comedy.",
     "source": "Patreon Top Creators 2024", "sourceUrl": "https://influencermarketinghub.com/patreon-stats-revenue-users/", "verified": True},
    {"id": 27, "name": "the yard podcast", "platform": "Patreon", "category": "Digital Creators/Innovators",
     "before": "New podcast seeking sustainable funding", "after": "Top 10 Patreon earner",
     "timeline": "2 years", "earnings": "£180,000/month", "highlight": "£224K earned in single month",
     "story": "The Yard grew their Patreon to over 35,000 patrons, earning £224,719 in June 2024 alone. Their engaging content and consistent release schedule kept subscribers coming back month after month, demonstrating how podcasters can build significant recurring revenue.",
     "source": "Patreon Earnings Report", "sourceUrl": "https://influencermarketinghub.com/patreon-stats-revenue-users/", "verified": True},
    {"id": 28, "name": "Andrea B.", "platform": "Udemy", "category": "Teaching & Tutoring",
     "before": "Developer with teaching skills", "after": "Course creator with consistent monthly income",
     "timeline": "2 years", "earnings": "£3,400/month average", "highlight": "Consistent £4,250/month from courses",
     "story": "Andrea created Flutter and Dart development courses on Udemy, focusing on practical, project-based learning. Through strategic course updates, student engagement, and building an email list, he achieved average monthly earnings of £4,250, providing stable passive income alongside his development work.",
     "source": "Udemy Instructor Earnings", "sourceUrl": "https://bloggingx.com/udemy-course-creator-earnings/", "verified": True},
    {"id": 29, "name": "Maria D.", "platform": "PeoplePerHour", "category": "Freelancing",
     "before": "Solo designer overwhelmed with work", "after": "Design business owner with team",
     "timeline": "1 year", "earnings": "Scaled business income", "highlight": "Solo to team-based design business",
     "story": "Maria was an active freelancer and buyer on PeoplePerHour. When her design business grew beyond what she could handle alone, she hired platform freelancers for projects like website redesigns. The quality exceeded expectations, enabling her to scale and take on more clients.",
     "source": "PeoplePerHour Business Growth", "sourceUrl": "https://www.peopleperhour.com/discover/stories/how-freelancers-on-peopleperhour-helped-maria-build-a-thriving-design-team/", "verified": True},
    {"id": 30, "name": "Anonymous Creator", "platform": "Redbubble", "category": "Digital Creators/Innovators",
     "before": "Part-time designer", "after": "True passive income earner",
     "timeline": "4+ years", "earnings": "£200+ in single month (passive)", "highlight": "3 years inactive, still earning",
     "story": "This creator uploaded at least 100 designs to Redbubble and then stopped uploading entirely in 2021. Despite no new designs or marketing for over 3 years, their inactive account earned over £200 in December 2024 alone from evergreen designs that continue selling via organic traffic.",
     "source": "Passive Redbubble Case Study", "sourceUrl": "https://www.youtube.com/watch?v=02IEPo__I2E", "verified": True},
    {"id": 31, "name": "Michael E.", "platform": "Redbubble", "category": "Digital Creators/Innovators",
     "before": "Designer seeking passive income", "after": "£1,000+/month print-on-demand seller",
     "timeline": "3 years", "earnings": "£1,000+/month", "highlight": "Strategic SEO approach works",
     "story": "Michael developed a strategic approach to Redbubble, focusing on SEO-optimized uploads and trending niches. By consistently uploading quality designs and optimizing titles and tags, he built a portfolio generating over £1,000 monthly. He shares his tactics through his blog.",
     "source": "Redbubble Success Guide", "sourceUrl": "https://www.michaelessek.com/sell-on-redbubble/", "verified": True},
    {"id": 32, "name": "Helen T.", "platform": "Swagbucks", "category": "Surveys & Research",
     "before": "Retired with time to spare", "after": "Consistent earner from multiple activities",
     "timeline": "6 months", "earnings": "£150-£250/month", "highlight": "Multiple earning methods combined",
     "story": "Helen discovered Swagbucks after retirement and found it perfect for her schedule. Beyond surveys, she earns from cashback shopping, watching videos, and playing games. By being consistent and strategic, she earns £150-250 monthly, which she uses for grandchildren's gifts.",
     "source": "Swagbucks User Guide", "sourceUrl": "https://www.swagbucks.com/articles/the-ultimate-guide-to-earning-paypal-cash-by-taking-online-surveys", "verified": True},
    {"id": 33, "name": "Alex K.", "platform": "Survey Junkie", "category": "Surveys & Research",
     "before": "Student needing pocket money", "after": "Regular survey income",
     "timeline": "3 months", "earnings": "£40/month", "highlight": "Covers monthly subscriptions",
     "story": "Alex signed up for Survey Junkie as a university student. By completing 3 surveys daily during study breaks, he consistently earns around £40 monthly. While not life-changing, it covers his streaming subscriptions and occasional takeaway without impacting his studies.",
     "source": "Survey Site Comparison", "sourceUrl": "https://whop.com/blog/swagbucks-vs-survey/", "verified": True},
    {"id": 34, "name": "Cinna (Brittany W.)", "platform": "Twitch", "category": "Digital Creators/Innovators",
     "before": "Growing streamer with loyal audience", "after": "Top female Twitch streamer",
     "timeline": "2 years", "earnings": "Top-tier streamer income", "highlight": "Won Best Female Streamer 2024",
     "story": "Cinna built a loyal community through consistent streaming and genuine engagement with viewers. Her audience grew from thousands to hundreds of thousands of followers by 2024. She won the Sapphire Award for Best Female Streamer at the 2024 Streamer Awards.",
     "source": "2024 Streamer Awards", "sourceUrl": "https://streamscharts.com/news/breakout-and-debutant-streamers-2024", "verified": True},
    {"id": 35, "name": "Arky", "platform": "Twitch", "category": "Digital Creators/Innovators",
     "before": "New streamer in 2024", "after": "Breakout star with massive TikTok presence",
     "timeline": "1 year", "earnings": "Rapid growth from 0", "highlight": "3.5M+ TikTok likes drove Twitch growth",
     "story": "Arky debuted on Twitch in 2024 with a unique strategy: creating short-form TikTok clips from his streams. With over 500 TikTok posts generating 3.5+ million likes, he drove massive traffic to his Twitch channel, rapidly growing among North American viewers.",
     "source": "StreamCharts 2024 Breakout Report", "sourceUrl": "https://streamscharts.com/news/breakout-and-debutant-streamers-2024", "verified": True},
    {"id": 36, "name": "Misterarther", "platform": "Twitch", "category": "Digital Creators/Innovators",
     "before": "German streamer seeking growth", "after": "2024 Rising Star Award winner",
     "timeline": "1 year", "earnings": "Rising star earnings", "highlight": "Won 2024 Rising Star Award",
     "story": "Misterarther pivoted to Just Chatting content and strategically collaborated with top North American streamers. This cross-cultural approach exposed him to new audiences, resulting in explosive growth and winning the Rising Star Award at the 2024 Streamer Awards.",
     "source": "2024 Streamer Awards", "sourceUrl": "https://streamscharts.com/news/breakout-and-debutant-streamers-2024", "verified": True},
    {"id": 37, "name": "Robert H.", "platform": "Substack", "category": "Digital Creators/Innovators",
     "before": "Writer with ideas to share", "after": "Successful newsletter with paid subscribers",
     "timeline": "2 years", "earnings": "Substantial subscriber income", "highlight": "Quality content drives conversions",
     "story": "Robert started writing about psychology and culture on Substack. By consistently publishing quality content and engaging with readers, he built a substantial paid subscriber base. He shares insights about earning and growing on the platform through his writing.",
     "source": "Substack Writer Insights", "sourceUrl": "https://www.robkhenderson.com/p/what-ive-learned-after-two-years", "verified": True},
    {"id": 38, "name": "Jamie S.", "platform": "Deliveroo", "category": "Gig Economy",
     "before": "Between jobs", "after": "Steady gig economy income",
     "timeline": "3 months", "earnings": "£10-£20/hour", "highlight": "Flexible income while job hunting",
     "story": "Jamie signed up for Deliveroo while job hunting in Birmingham. Using a bicycle, he learned the city's fastest routes and which restaurants were quickest. On good nights, he earns £15-20/hour. The flexibility let him attend interviews while still earning.",
     "source": "Gig Economy Earnings Data", "sourceUrl": "https://www.breakroom.cc/en-gb/employers/deliveroo/pay", "verified": True},
    {"id": 39, "name": "Nina K.", "platform": "Vinted", "category": "E-commerce",
     "before": "Overwhelmed by wardrobe clutter", "after": "Regular seller with tidy home",
     "timeline": "4 months", "earnings": "£500+ in 4 months", "highlight": "Decluttered and earned",
     "story": "Nina discovered Vinted when trying to declutter her home. Starting with a few items, she was surprised how quickly things sold. The lack of seller fees meant she kept all profits. She's earned £500+ and gained a much more organized living space.",
     "source": "Vinted User Success", "sourceUrl": "https://www.rhianwestbury.co.uk/2024/02/from-closet-to-cash-a-vinted-update.html", "verified": True},
    {"id": 40, "name": "Peter L.", "platform": "Prolific", "category": "Surveys & Research",
     "before": "Looking for legitimate survey income", "after": "Trusted Prolific participant",
     "timeline": "6 months", "earnings": "£6-£12/hour consistently", "highlight": "Fair academic research pay",
     "story": "Peter was frustrated with traditional survey sites that disqualified him constantly. On Prolific, the academic research focus meant surveys were matched to his profile. He averages £6-12/hour and appreciates the interesting topics covering psychology and social science.",
     "source": "Prolific Review", "sourceUrl": "https://hardlyhamilton.com/2024/02/04/make-money-online-prolific/", "verified": True},
    {"id": 41, "name": "Grace M.", "platform": "Ko-fi", "category": "Digital Creators/Innovators",
     "before": "Artist relying on commission work", "after": "Diversified income through memberships",
     "timeline": "8 months", "earnings": "Monthly membership income", "highlight": "0% platform fees on donations",
     "story": "Grace set up her Ko-fi page to supplement commission work. She offered monthly memberships with exclusive art process videos and early access to prints. The 0% fee on donations meant she kept everything supporters gave. Her supporters now fund her creative freedom.",
     "source": "Ko-fi Creator Guide", "sourceUrl": "https://more.ko-fi.com/academy", "verified": True},
    {"id": 42, "name": "Pomplamoose", "platform": "Patreon", "category": "Digital Creators/Innovators",
     "before": "Musicians seeking sustainable income", "after": "Longest-running Patreon creator since 2013",
     "timeline": "11+ years", "earnings": "£6,000/month average", "highlight": "Longest-running Patreon since 2013",
     "story": "This musical duo became one of Patreon's earliest and longest-running creators. By offering exclusive music, behind-the-scenes content, and direct fan access, they've maintained a loyal patronage for over a decade, averaging around £7,500 monthly.",
     "source": "Patreon Long-term Creator Report", "sourceUrl": "https://influencermarketinghub.com/patreon-stats-revenue-users/", "verified": True},
    {"id": 43, "name": "Christina L.", "platform": "Udemy", "category": "Teaching & Tutoring",
     "before": "Expert wanting to teach online", "after": "Course creator with growing income",
     "timeline": "3 months", "earnings": "£34+ first month, growing", "highlight": "First course earned immediately",
     "story": "Christina created her first Udemy course and earned £42.83 in her first month. While modest, it validated her teaching approach. She's continued improving her course and marketing, steadily growing her student base and income month over month.",
     "source": "New Udemy Instructor Report", "sourceUrl": "https://instructor-academy.onlinecoursehost.com/how-much-do-udemy-instructors-make/", "verified": True},
    {"id": 44, "name": "Nick P.", "platform": "Udemy", "category": "Teaching & Tutoring",
     "before": "Professional with niche expertise", "after": "Passive course income earner",
     "timeline": "2 years", "earnings": "£150/month passive", "highlight": "Single course, minimal effort",
     "story": "Nick created one comprehensive course in his area of expertise. Without aggressive marketing or additional courses, it generates approximately £1,800 yearly (about £150/month). It's not life-changing, but it's truly passive income requiring minimal maintenance.",
     "source": "Passive Udemy Income", "sourceUrl": "https://instructor-academy.onlinecoursehost.com/how-much-do-udemy-instructors-make/", "verified": True},
    {"id": 45, "name": "Daniel W.", "platform": "Gumroad", "category": "Digital Creators/Innovators",
     "before": "Creator with ebook idea", "after": "Multi-year ebook seller",
     "timeline": "2+ years", "earnings": "£11,000+ from one ebook", "highlight": "£14K+ from single ebook",
     "story": "Daniel launched an ebook on Gumroad in 2022 covering his area of expertise. With Gumroad handling all payment processing and delivery, he focused on marketing. His ebook has generated over £14,000 in sales, proving digital products can provide long-term income.",
     "source": "Gumroad Creator Review", "sourceUrl": "https://selfmademillennials.com/gumroad-review/", "verified": True},
    {"id": 46, "name": "Sam B.", "platform": "TaskRabbit", "category": "Gig Economy",
     "before": "Handy person between jobs", "after": "Busy local task earner",
     "timeline": "2 months", "earnings": "£800-£1,200/month", "highlight": "5-star reviews drive bookings",
     "story": "Sam signed up for TaskRabbit to do furniture assembly and minor repairs. His attention to detail led to 5-star reviews, which brought more bookings. On weekends, he completes 4-5 tasks, earning £200-300. The flexibility lets him control his schedule completely.",
     "source": "TaskRabbit Success Story", "sourceUrl": "https://taskrabbit.com", "verified": True},
    {"id": 47, "name": "Amanda J.", "platform": "Qmee", "category": "Surveys & Research",
     "before": "Looking for no-minimum payout surveys", "after": "Regular micro-earner",
     "timeline": "4 months", "earnings": "£50-£100/month", "highlight": "Instant PayPal withdrawals",
     "story": "Amanda loved that Qmee has no minimum payout threshold - she could withdraw immediately. She earns from surveys, shopping cashback, and search rewards. While individual amounts are small, instant PayPal withdrawals make it feel like finding money in her pocket.",
     "source": "Qmee User Review", "sourceUrl": "https://www.qmee.com/en-gb", "verified": True},
    {"id": 48, "name": "William R.", "platform": "YouGov", "category": "Surveys & Research",
     "before": "Politically engaged individual", "after": "Regular opinion poll participant",
     "timeline": "1 year", "earnings": "£30-£50/month", "highlight": "Contributing to real research",
     "story": "William enjoys seeing YouGov poll results in news articles and wanted to participate. By consistently completing surveys on politics, culture, and consumer topics, he earns £30-50 monthly. Beyond money, he values contributing to respected research.",
     "source": "YouGov Panel Experience", "sourceUrl": "https://account.yougov.com/gb-en/join/main", "verified": True},
    {"id": 49, "name": "Kelly O.", "platform": "Pinecone Research", "category": "Surveys & Research",
     "before": "Survey taker seeking consistency", "after": "Reliable survey income earner",
     "timeline": "8 months", "earnings": "£70-£90/month", "highlight": "Flat £3 per survey, plus free products",
     "story": "Kelly was invited to join Pinecone Research, an exclusive panel. Every survey pays exactly £3, making earnings predictable. She also receives products to test at home. The consistency and product testing perks make it her favorite survey site.",
     "source": "Pinecone Research Review", "sourceUrl": "https://www.pineconeresearch.com", "verified": True},
    {"id": 50, "name": "Trevor M.", "platform": "Branded Surveys", "category": "Surveys & Research",
     "before": "New to online surveys", "after": "Loyal survey taker with bonuses",
     "timeline": "6 months", "earnings": "£100-£150/month", "highlight": "Loyalty bonuses add up",
     "story": "Trevor found Branded Surveys' loyalty program rewarding. The more surveys he completed, the higher his bonus tier grew. Combined with daily polls and quick surveys, he earns £100-150 monthly. The low £5 payout threshold means frequent cash outs.",
     "source": "Branded Surveys Success", "sourceUrl": "https://surveys.gobranded.com", "verified": True},
    {"id": 51, "name": "Lucy H.", "platform": "Attapoll", "category": "Surveys & Research",
     "before": "Mobile-first survey seeker", "after": "On-the-go survey earner",
     "timeline": "3 months", "earnings": "£20-£50/month", "highlight": "£3 minimum payout",
     "story": "Lucy wanted to earn from surveys on her phone during commutes. Attapoll's mobile app had a clean interface and low £3 payout threshold. Surveys are well-matched to her profile, reducing frustrating disqualifications. She earns £20-50 monthly from idle moments.",
     "source": "Attapoll Mobile Surveys", "sourceUrl": "https://attapoll.app", "verified": True},
    {"id": 52, "name": "George T.", "platform": "Skillshare", "category": "Teaching & Tutoring",
     "before": "Designer wanting to teach", "after": "Online teacher with royalty income",
     "timeline": "1 year", "earnings": "£200-£500/month", "highlight": "Royalties from minutes watched",
     "story": "George created video classes about design software on Skillshare. He earns royalties based on minutes watched by premium subscribers. With 12+ million learners on the platform, his classes found an audience. Referral bonuses add to his monthly earnings.",
     "source": "Skillshare Teacher Program", "sourceUrl": "https://www.skillshare.com/teach", "verified": True},
    {"id": 53, "name": "Olivia N.", "platform": "We Work Remotely", "category": "Remote Jobs",
     "before": "Office worker wanting flexibility", "after": "Fully remote professional",
     "timeline": "2 months", "earnings": "£4,500+/month", "highlight": "Found quality remote role quickly",
     "story": "Olivia found her current role through We Work Remotely. The site's curated remote job listings from companies like Google and Amazon made her job search efficient. She now works from home for a tech company, earning more than her previous office role.",
     "source": "We Work Remotely Success", "sourceUrl": "https://weworkremotely.com", "verified": True},
    {"id": 54, "name": "Henry B.", "platform": "FlexJobs", "category": "Remote Jobs",
     "before": "Skeptical about remote work sites", "after": "Remote job finder",
     "timeline": "1 month", "earnings": "£2,500/month", "highlight": "Verified, scam-free listings",
     "story": "Henry was tired of scam job listings. FlexJobs' curated, verified remote opportunities gave him confidence. He found a legitimate remote customer support role within weeks. The subscription fee was worth avoiding fake listings and saving time.",
     "source": "FlexJobs User Story", "sourceUrl": "https://flexjobs.com", "verified": True},
    {"id": 55, "name": "Rebecca S.", "platform": "InboxDollars", "category": "Surveys & Research",
     "before": "Multi-tasker wanting extra income", "after": "Diverse earner on one platform",
     "timeline": "5 months", "earnings": "£80-£150/month", "highlight": "Real cash, not confusing points",
     "story": "Rebecca liked that InboxDollars combined surveys with cashback shopping, video watching, and game playing. The £5 signup bonus got her started. Surveys pay in actual cash amounts rather than confusing points, making earnings transparent.",
     "source": "InboxDollars Multi-Earning", "sourceUrl": "https://www.inboxdollars.com", "verified": True},
    {"id": 56, "name": "Paul J.", "platform": "PrizeRebel", "category": "Surveys & Research",
     "before": "GPT site newcomer", "after": "Tiered member with 30% bonuses",
     "timeline": "8 months", "earnings": "£80-£200/month", "highlight": "30% loyalty bonus tier",
     "story": "Paul discovered PrizeRebel's tiered loyalty system rewarded consistent users. As he completed more surveys and offers, his bonus percentage grew to 30%. Daily challenges and contests add extra earning opportunities. The low £2 payout threshold keeps motivation high.",
     "source": "PrizeRebel Loyalty Program", "sourceUrl": "https://www.prizerebel.com", "verified": True},
    {"id": 57, "name": "Natalie D.", "platform": "Toluna", "category": "Surveys & Research",
     "before": "Survey taker wanting variety", "after": "Active community member",
     "timeline": "6 months", "earnings": "£50-£120/month", "highlight": "Product testing opportunities",
     "story": "Natalie joined Toluna's 21+ million member community. Beyond surveys, she participates in polls and product testing opportunities. Points convert to cash or gift cards. The mobile app makes completing surveys convenient during her daily routine.",
     "source": "Toluna Community", "sourceUrl": "https://www.toluna.com", "verified": True},
    {"id": 58, "name": "Charlie F.", "platform": "Forthright", "category": "Surveys & Research",
     "before": "Frustrated with minimum payouts", "after": "Instant payment survey taker",
     "timeline": "2 months", "earnings": "£40-£80/month", "highlight": "Instant payment per survey",
     "story": "Charlie loved Forthright's unique approach: instant PayPal payments after each survey. No points, no minimum thresholds - just complete a survey and get paid immediately. The clean mobile experience makes it easy to earn during any spare moment.",
     "source": "Forthright Instant Pay", "sourceUrl": "https://www.forthright.com", "verified": True},
    {"id": 59, "name": "Ben A.", "platform": "Remote OK", "category": "Remote Jobs",
     "before": "Developer seeking remote roles", "after": "Remote developer",
     "timeline": "3 weeks", "earnings": "£5,000+/month", "highlight": "Salary stats helped negotiation",
     "story": "Ben used Remote OK to find development jobs matching his skills. The site aggregates remote opportunities and shows salary statistics to help negotiate. Free job alerts notified him instantly when matching positions opened. He landed a role paying more than expected.",
     "source": "Remote OK Job Search", "sourceUrl": "https://remoteok.com", "verified": True},
    {"id": 60, "name": "Emily C.", "platform": "Google Opinion Rewards", "category": "Surveys & Research",
     "before": "Android user wanting free apps", "after": "Consistent micro-earner",
     "timeline": "1 year", "earnings": "£60-£100/year", "highlight": "Quick surveys fund app purchases",
     "story": "Emily downloaded Google Opinion Rewards and answers quick location-based surveys. Each pays £0.10-£1 and takes under a minute. Over a year, she's earned £80+ in Google Play credit, funding app purchases and game extras she'd never buy otherwise.",
     "source": "Google Opinion Rewards", "sourceUrl": "https://surveys.google.com/google-opinion-rewards/", "verified": True},
]


def _build():
    seen = set()
    out = []
    for s in _RAW:
        base = _slugify(f"{s['name']}-{s['platform']}")
        slug = base if base else f"story-{s['id']}"
        if slug in seen:
            slug = f"{slug}-{s['id']}"
        seen.add(slug)
        out.append({**s, "slug": slug})
    return out


STORIES = _build()
STORIES_BY_SLUG = {s["slug"]: s for s in STORIES}


def get_all():
    return STORIES


def get_by_slug(slug: str):
    return STORIES_BY_SLUG.get((slug or "").lower().strip())


def get_related(story: dict, limit: int = 4):
    """Same-category stories first, then same-platform, excluding self."""
    if not story:
        return []
    out, seen = [], {story["slug"]}
    for s in STORIES:
        if s["slug"] in seen:
            continue
        if s["category"] == story["category"]:
            out.append(s)
            seen.add(s["slug"])
    for s in STORIES:
        if len(out) >= limit:
            break
        if s["slug"] in seen:
            continue
        if s["platform"] == story["platform"]:
            out.append(s)
            seen.add(s["slug"])
    return out[:limit]
